import type { FeatureIconKey } from "~/config/site";
import type { LocaleCode } from "~/config/localization";

// Translated descriptions for the home feature cards, showcases and workflow
// steps in the locales whose landing copy is otherwise compact (one shared
// description per group). Order follows FEATURE_SHOWCASES and WORKFLOW_STEPS.
export type HomeDescriptions = {
  features: Partial<Record<FeatureIconKey, string>>;
  showcases: string[];
  workflow: string[];
};

export const HOME_DESCRIPTIONS: Partial<Record<Exclude<LocaleCode, "en">, HomeDescriptions>> = {
  zh: {
    features: {
      templates: "改一次，所有变体同步更新。修改任意形状或文字，改动会同时应用到你的全部截图。",
      project: "81 种语言预设，从英语到阿拉伯语、印地语以及中日韩文字。自动翻译缺失文案，再按形状微调文本、位置和图片覆盖，并可追踪翻译进度。",
      export: "按每一行的精确像素尺寸导出 PNG 或 JPEG，一次覆盖所有语言。文件夹按语言和行自动整理，可直接用于 App Store Connect、Google Play 和发布素材。",
      cloud: "可选的 iCloud Drive 同步让项目在你的 Mac、iPad 和 iPhone 之间随时可用。采用以最后写入为准的合并策略，并配合可识别删除标记（tombstone）的冲突解决机制。",
      native: "使用 Swift 和 SwiftUI 为 Mac、iPad 和 iPhone 打造。没有 Electron，也不是浏览器标签页。秒速启动、原生性能、自动保存、完整的撤销/重做。",
      fonts: "导入你自己的 .ttf、.otf 或 .ttc 字体文件。文字形状可使用任意字体，不受系统字体限制。",
      privacy: "自动翻译通过 Apple 的 Translation 框架在设备端运行。无需 API 密钥，无需账号，没有广告追踪——项目、字体和截图都保留在你的设备上。",
      free: "1 个项目、3 行、每行 5 个模板——包含所有设备边框、全部 81 种语言和所有导出格式。无水印、无试用期限、无需注册。",
    },
    showcases: [
      "一次拖入多张截图——Screenshot Bro 会全部导入，并自动为每一张套上设备边框。无需手动摆放，也不用一张一张繁琐处理。",
      "只需连接一次 App Store Connect API 密钥，即可把渲染好的截图直接推送到正确的应用、版本、显示类型和语言。自动识别显示类型、匹配语言、上传前预检，一次完成替换——无需在浏览器里拖放。",
      "添加矩形、圆形、星形、文字、图片和 SVG，然后逐个调整大小、旋转和设置样式。直接在检查器中设置填充颜色、渐变、不透明度、描边和圆角。叠放图层，按住 Shift 拖动锁定宽高比，并吸附到像素级精准对齐。",
      "从 16 种渐变预设中选择，用多色标编辑器自己打造，或放入图片并选择填充、适应、拉伸和平铺模式。背景可以横跨一行中的多个模板，实现无缝衔接的通栏设计。调整角度、不透明度和色标——一切实时更新。",
      "从设备边框库中挑选——iPhone、iPad、MacBook、iMac 以及 Android 手机和平板。更换边框、选择机身颜色、贴合你的品牌，无需重新导入截图。",
      "开启本地 MCP 服务器后，Claude Code、Claude Desktop 或 Cursor 就能操控 Screenshot Bro：创建项目、排布行和形状、导入截图、翻译文案、查看渲染预览、导出，并将整套截图同步到 App Store Connect。它只监听 127.0.0.1，需要使用设置中的令牌，每项更改都可用 ⌘Z 撤销。",
    ],
    workflow: [
      "选择设备尺寸——iPhone、iPad、Mac，或 Android 手机和平板，每种都预设为对应商店要求的像素。需要多少行就添加多少行。",
      "放入设备边框，添加文字和形状，选择背景。添加语言，自动翻译缺失文案，并按形状微调文本覆盖，让每种语言都保持像素级完美。",
      "点击导出。得到按语言和行整理好的文件夹，每张截图都是商店要求的精确尺寸。一键完成。",
      "只需连接一次 API 密钥，即可把截图直接推送到正确的应用、版本、显示类型和语言——无需手动拖放到浏览器中。",
    ],
  },
  hi: {
    features: {
      templates: "एक बार एडिट करें, हर वेरिएंट अपडेट। किसी शेप या टेक्स्ट को बदलें और बदलाव आपके सभी screenshots में एक साथ लागू हो जाता है।",
      project: "अंग्रेज़ी से लेकर अरबी, हिंदी और CJK तक 81 भाषा प्रीसेट। छूटी हुई कॉपी ऑटो-ट्रांसलेट करें, फिर हर शेप का टेक्स्ट, पोज़िशन और इमेज ओवरराइड बारीकी से सेट करें, साथ में अनुवाद की प्रगति भी ट्रैक करें।",
      export: "हर पंक्ति के सटीक पिक्सेल साइज़ पर PNG या JPEG एक्सपोर्ट करें, सभी लोकेल के लिए एक साथ। App Store Connect, Google Play और launch assets के लिए फ़ोल्डर लोकेल और पंक्ति के हिसाब से अपने-आप व्यवस्थित होते हैं।",
      cloud: "वैकल्पिक iCloud Drive सिंक आपके प्रोजेक्ट्स को आपके Mac, iPad और iPhone पर उपलब्ध रखता है। Last-writer-wins मर्ज और tombstone-aware conflict resolution के साथ।",
      native: "Mac, iPad और iPhone के लिए Swift और SwiftUI से बना। न Electron, न ब्राउज़र टैब। तुरंत लॉन्च, नेटिव परफ़ॉर्मेंस, ऑटो-सेव, पूरा undo/redo।",
      fonts: "अपनी .ttf, .otf या .ttc फ़ॉन्ट फ़ाइलें इंपोर्ट करें। टेक्स्ट शेप्स में कोई भी टाइपफ़ेस इस्तेमाल करें — सिस्टम फ़ॉन्ट की कोई सीमा नहीं।",
      privacy: "ऑटो-ट्रांसलेट Apple के Translation framework के ज़रिए डिवाइस पर ही चलता है। न API keys, न अकाउंट, न ऐड ट्रैकिंग — प्रोजेक्ट्स, फ़ॉन्ट और screenshots आपके डिवाइस पर ही रहते हैं।",
      free: "1 प्रोजेक्ट, 3 पंक्तियां, हर पंक्ति में 5 टेम्पलेट — हर डिवाइस फ्रेम, सभी 81 लोकेल और हर एक्सपोर्ट फ़ॉर्मेट के साथ। न वॉटरमार्क, न ट्रायल की समय-सीमा, न साइनअप।",
    },
    showcases: [
      "एक साथ कई screenshots ड्रैग और ड्रॉप करें — Screenshot Bro सबको इंपोर्ट करता है और हर एक को अपने-आप डिवाइस फ्रेम में फिट कर देता है। न मैन्युअल प्लेसमेंट, न एक-एक करके थकाऊ काम।",
      "अपनी App Store Connect API key एक बार कनेक्ट करें, फिर रेंडर किए गए screenshots सीधे सही ऐप, वर्ज़न, डिस्प्ले टाइप और लोकेल पर भेजें। अपने-आप पहचाने गए डिस्प्ले टाइप, लोकेल मैचिंग, preflight checks और एक बार में replace — ब्राउज़र में कोई ड्रैग-एंड-ड्रॉप नहीं।",
      "आयत, वृत्त, स्टार, टेक्स्ट, इमेज और SVG जोड़ें — फिर हर एक का साइज़ बदलें, घुमाएं और स्टाइल करें। इंस्पेक्टर से ही fill colors, ग्रेडिएंट, opacity, outlines और corner radius सेट करें। लेयर्स को स्टैक करें, aspect ratio लॉक करने के लिए Shift-drag करें, और pixel-perfect अलाइनमेंट पर snap करें।",
      "16 ग्रेडिएंट प्रीसेट में से चुनें, multi-stop एडिटर से अपना ग्रेडिएंट बनाएं, या fill, fit, stretch और tile मोड के साथ इमेज डालें। सहज, edge-to-edge डिज़ाइन के लिए बैकग्राउंड एक पंक्ति के कई टेम्पलेट्स में फैल सकते हैं। एंगल, opacity और color stops बदलें — सब कुछ लाइव अपडेट होता है।",
      "डिवाइस बेज़ल की लाइब्रेरी से चुनें — iPhone, iPad, MacBook, iMac और Android फ़ोन व टैबलेट। फ्रेम बदलें, बॉडी कलर चुनें और screenshots दोबारा इंपोर्ट किए बिना अपने ब्रांड से मैच करें।",
      "लोकल MCP सर्वर चालू करें और Claude Code, Claude Desktop या Cursor Screenshot Bro को चला सकते हैं: प्रोजेक्ट बनाना, पंक्तियां और शेप्स लेआउट करना, screenshots इंपोर्ट करना, कॉपी ट्रांसलेट करना, रेंडर किए गए प्रीव्यू देखना, एक्सपोर्ट करना और पूरा सेट App Store Connect पर सिंक करना। यह केवल 127.0.0.1 पर सुनता है, इसके लिए Settings से मिला टोकन चाहिए, और हर बदलाव ⌘Z से undo हो जाता है।",
    ],
    workflow: [
      "अपने डिवाइस साइज़ चुनें — iPhone, iPad, Mac, या Android फ़ोन और टैबलेट, हर एक उसी पिक्सेल साइज़ पर प्रीसेट जो उसका स्टोर चाहता है। जितनी चाहें उतनी पंक्तियां जोड़ें।",
      "डिवाइस फ्रेम डालें, टेक्स्ट और शेप्स जोड़ें, बैकग्राउंड चुनें। लोकेल जोड़ें, छूटी हुई कॉपी ऑटो-ट्रांसलेट करें, और हर शेप के टेक्स्ट ओवरराइड ट्यून करें ताकि हर भाषा pixel-perfect रहे।",
      "एक्सपोर्ट दबाएं। लोकेल और पंक्ति के हिसाब से व्यवस्थित फ़ोल्डर पाएं, हर screenshot ठीक उसी साइज़ में जो स्टोर चाहता है। बस एक क्लिक।",
      "अपनी API key एक बार कनेक्ट करें, फिर screenshots सीधे सही ऐप, वर्ज़न, डिस्प्ले टाइप और लोकेल पर भेजें — ब्राउज़र में मैन्युअल ड्रैग-एंड-ड्रॉप की ज़रूरत नहीं।",
    ],
  },
  fr: {
    features: {
      templates: "Modifiez une fois, toutes les variantes suivent. Changez une forme ou un texte : la modification s'applique simultanément à toutes vos captures.",
      project: "81 langues prédéfinies, de l'anglais à l'arabe, l'hindi et le CJK. Traduisez automatiquement les textes manquants, puis affinez par forme le texte, la position et les images, avec un suivi de l'avancement des traductions.",
      export: "Exportez en PNG ou JPEG à la taille exacte en pixels de chaque rangée, pour toutes les langues en une fois. Dossiers classés automatiquement par langue et par rangée pour App Store Connect, Google Play et vos visuels de lancement.",
      cloud: "La synchronisation iCloud Drive, à activer si vous le souhaitez, garde vos projets disponibles sur tous vos Mac, iPad et iPhone. Fusion selon le principe « la dernière écriture l'emporte » et résolution des conflits qui tient compte des éléments supprimés.",
      native: "Conçue en Swift et SwiftUI pour Mac, iPad et iPhone. Pas d'Electron, pas d'onglet de navigateur. Lancement instantané, performances natives, sauvegarde automatique, annuler/rétablir complet.",
      fonts: "Importez vos propres fichiers de police .ttf, .otf ou .ttc. Utilisez n'importe quelle typo dans les formes de texte, sans vous limiter aux polices système.",
      privacy: "La traduction automatique s'exécute sur l'appareil via le framework Translation d'Apple. Pas de clé API, pas de compte, pas de pistage publicitaire : projets, polices et captures restent sur votre appareil.",
      free: "1 projet, 3 rangées, 5 modèles par rangée — avec tous les cadres d'appareils, les 81 langues et tous les formats d'export. Pas de filigrane, pas d'essai qui expire, pas d'inscription.",
    },
    showcases: [
      "Glissez-déposez plusieurs captures d'un coup : Screenshot Bro les importe toutes et place automatiquement chacune dans son cadre d'appareil. Pas de placement manuel, pas de traitement fastidieux une par une.",
      "Connectez votre clé API App Store Connect une seule fois, puis envoyez les captures rendues directement vers la bonne app, la bonne version, le bon type d'écran et la bonne langue. Types d'écran détectés automatiquement, correspondance des langues, vérifications préalables et remplacement en une seule passe — sans glisser-déposer dans le navigateur.",
      "Ajoutez rectangles, cercles, étoiles, textes, images et SVG, puis redimensionnez, faites pivoter et stylisez chaque élément. Réglez couleurs de remplissage, dégradés, opacité, contours et rayon des coins directement dans l'inspecteur. Empilez les calques, glissez avec Maj pour verrouiller les proportions et alignez tout au pixel près grâce au magnétisme.",
      "Choisissez parmi 16 dégradés prédéfinis, créez le vôtre avec l'éditeur multi-points ou ajoutez des images en mode remplir, ajuster, étirer ou mosaïque. Les arrière-plans peuvent s'étendre sur plusieurs modèles d'une rangée pour des designs continus, bord à bord. Réglez l'angle, l'opacité et les points de couleur : tout se met à jour en direct.",
      "Choisissez dans une bibliothèque de cadres d'appareils — iPhone, iPad, MacBook, iMac, ainsi que téléphones et tablettes Android. Changez de cadre, choisissez la couleur du boîtier et accordez le tout à votre marque sans réimporter vos captures.",
      "Activez le serveur MCP local, et Claude Code, Claude Desktop ou Cursor peuvent piloter Screenshot Bro : créer un projet, organiser rangées et formes, importer des captures, traduire les textes, examiner les aperçus rendus, exporter et synchroniser l'ensemble avec App Store Connect. Il écoute uniquement sur 127.0.0.1, exige un jeton issu des Réglages, et chaque modification s'annule avec ⌘Z.",
    ],
    workflow: [
      "Choisissez vos tailles d'appareils — iPhone, iPad, Mac, ou téléphone et tablette Android, chacun préréglé aux dimensions en pixels attendues par son store. Ajoutez autant de rangées que nécessaire.",
      "Ajoutez des cadres d'appareils, du texte et des formes, puis choisissez un arrière-plan. Ajoutez des langues, traduisez automatiquement les textes manquants et ajustez le texte forme par forme pour que chaque langue reste parfaite au pixel près.",
      "Lancez l'export. Vous obtenez des dossiers classés par langue et par rangée, chaque capture à la taille exacte attendue par le store. En un clic.",
      "Connectez votre clé API une seule fois, puis envoyez les captures directement vers la bonne app, la bonne version, le bon type d'écran et la bonne langue — sans glisser-déposer manuel dans le navigateur.",
    ],
  },
  ar: {
    features: {
      templates: "عدّل مرة واحدة، فتتحدّث كل النسخ. غيّر شكلاً أو نصاً، وسينعكس التغيير على جميع لقطاتك في الوقت نفسه.",
      project: "81 لغة جاهزة، من الإنجليزية إلى العربية والهندية ولغات CJK. ترجم النصوص الناقصة تلقائياً، ثم اضبط بدقة النص والموضع والصور لكل شكل، مع تتبّع تقدّم الترجمة.",
      export: "صدّر بصيغة PNG أو JPEG بالحجم الدقيق بالبكسل لكل صف، ولكل اللغات دفعة واحدة. مجلدات منظّمة تلقائياً حسب اللغة والصف لـ App Store Connect و Google Play ومواد الإطلاق.",
      cloud: "مزامنة iCloud Drive الاختيارية تُبقي مشاريعك متاحة على أجهزة Mac و iPad و iPhone. دمج يعتمد مبدأ «آخر تعديل هو الفائز»، مع حلّ للتعارضات يراعي العناصر المحذوفة.",
      native: "مبني باستخدام Swift و SwiftUI لأجهزة Mac و iPad و iPhone. بلا Electron، وبلا علامة تبويب في المتصفح. تشغيل فوري، وأداء أصلي، وحفظ تلقائي، وتراجع وإعادة بالكامل.",
      fonts: "استورد ملفات خطوطك بصيغ .ttf أو .otf أو .ttc. استخدم أي خط في أشكال النص — دون التقيّد بخطوط النظام.",
      privacy: "تعمل الترجمة التلقائية على الجهاز عبر إطار Translation من Apple. لا مفاتيح API، ولا حسابات، ولا تتبّع إعلاني — تبقى المشاريع والخطوط واللقطات على جهازك.",
      free: "1 مشروع، و3 صفوف، و5 قوالب لكل صف — مع جميع إطارات الأجهزة، وكل اللغات الـ81، وجميع صيغ التصدير. بلا علامة مائية، وبلا فترة تجريبية تنتهي، وبلا تسجيل.",
    },
    showcases: [
      "اسحب عدة لقطات وأفلتها دفعة واحدة — يستوردها Screenshot Bro كلها ويضع كل واحدة منها تلقائياً داخل إطار الجهاز. بلا وضع يدوي، وبلا عمل مملّ لقطةً تلو الأخرى.",
      "اربط مفتاح App Store Connect API مرة واحدة، ثم أرسل اللقطات المُصيَّرة مباشرة إلى التطبيق والإصدار ونوع العرض واللغة الصحيحة. أنواع عرض تُكتشف تلقائياً، ومطابقة للغات، وفحوصات مسبقة، واستبدال في خطوة واحدة — بلا سحب وإفلات في المتصفح.",
      "أضف مستطيلات ودوائر ونجوماً ونصوصاً وصوراً و SVG — ثم غيّر حجم كل منها ودوّره ونسّقه. اضبط ألوان التعبئة والتدرجات والشفافية والحدود ونصف قطر الزوايا مباشرة من المفتش. رتّب الطبقات فوق بعضها، واسحب مع Shift لتثبيت نسبة الأبعاد، واستفد من الالتقاط لمحاذاة دقيقة حتى البكسل.",
      "اختر من بين 16 تدرجاً جاهزاً، أو أنشئ تدرجك الخاص بمحرر متعدد النقاط، أو أضف صوراً بأوضاع التعبئة والملاءمة والتمديد والتكرار. يمكن للخلفيات أن تمتد عبر عدة قوالب في الصف لتصاميم متصلة من الحافة إلى الحافة. اضبط الزاوية والشفافية ونقاط الألوان — وكل شيء يتحدّث مباشرة.",
      "اختر من مكتبة إطارات الأجهزة — iPhone و iPad و MacBook و iMac وهواتف Android وأجهزتها اللوحية. بدّل الإطارات، واختر لون الهيكل، وطابق هويتك التجارية دون إعادة استيراد اللقطات.",
      "شغّل خادم MCP المحلي، وسيتمكن Claude Code أو Claude Desktop أو Cursor من التحكم في Screenshot Bro: إنشاء مشروع، وترتيب الصفوف والأشكال، واستيراد اللقطات، وترجمة النصوص، ومعاينة النتائج المُصيَّرة، والتصدير، ومزامنة المجموعة مع App Store Connect. يستمع على 127.0.0.1 فقط، ويحتاج إلى رمز من الإعدادات، ويمكن التراجع عن كل تغيير بـ ⌘Z.",
    ],
    workflow: [
      "اختر أحجام أجهزتك — iPhone أو iPad أو Mac أو هاتف وجهاز لوحي Android، وكل منها مضبوط مسبقاً على أبعاد البكسل التي يتطلبها متجره. أضف ما تحتاجه من صفوف.",
      "أضف إطارات الأجهزة والنصوص والأشكال، واختر خلفية. أضف اللغات، وترجم النصوص الناقصة تلقائياً، واضبط نص كل شكل لتبقى كل لغة دقيقة حتى البكسل.",
      "اضغط تصدير. ستحصل على مجلدات منظّمة حسب اللغة والصف، وكل لقطة بالحجم الدقيق الذي يتطلبه المتجر. بنقرة واحدة.",
      "اربط مفتاح API مرة واحدة، ثم أرسل اللقطات مباشرة إلى التطبيق والإصدار ونوع العرض واللغة الصحيحة — بلا سحب وإفلات يدوي في المتصفح.",
    ],
  },
  de: {
    features: {
      templates: "Einmal bearbeiten, jede Variante ist aktuell. Ändere eine Form oder einen Text, und die Änderung greift gleichzeitig in all deinen Screenshots.",
      project: "81 Sprachvorlagen von Englisch bis Arabisch, Hindi und CJK. Übersetze fehlende Texte automatisch und passe dann Text, Position und Bilder pro Form fein an — mit Fortschrittsanzeige für die Übersetzung.",
      export: "Exportiere PNG oder JPEG in der exakten Pixelgröße jeder Zeile, für alle Sprachen auf einmal. Automatisch nach Sprache und Zeile sortierte Ordner für App Store Connect, Google Play und Launch-Assets.",
      cloud: "Die optionale iCloud Drive-Synchronisierung hält deine Projekte auf all deinen Macs, iPads und iPhones verfügbar. Zusammenführung nach dem Last-Writer-Wins-Prinzip mit einer Konfliktlösung, die gelöschte Elemente (Tombstones) berücksichtigt.",
      native: "Mit Swift und SwiftUI für Mac, iPad und iPhone entwickelt. Kein Electron, kein Browser-Tab. Sofortiger Start, native Performance, automatisches Speichern, vollständiges Rückgängig/Wiederholen.",
      fonts: "Importiere deine eigenen Schriftdateien im Format .ttf, .otf oder .ttc. Nutze jede beliebige Schrift in Textformen — ohne Beschränkung auf Systemschriften.",
      privacy: "Die automatische Übersetzung läuft direkt auf dem Gerät über Apples Translation-Framework. Keine API-Schlüssel, keine Konten, kein Werbetracking — Projekte, Schriften und Screenshots bleiben auf deinem Gerät.",
      free: "1 Projekt, 3 Zeilen, 5 Templates pro Zeile — mit allen Geräterahmen, allen 81 Sprachen und allen Exportformaten. Kein Wasserzeichen, kein ablaufender Testzeitraum, keine Registrierung.",
    },
    showcases: [
      "Zieh mehrere Screenshots auf einmal hinein — Screenshot Bro importiert sie alle und setzt jeden automatisch in den Geräterahmen. Keine manuelle Platzierung, kein mühsames Abarbeiten Bild für Bild.",
      "Verbinde deinen App Store Connect API-Schlüssel einmal und schick gerenderte Screenshots direkt an die richtige App, Version, den richtigen Anzeigetyp und die richtige Sprache. Automatisch erkannte Anzeigetypen, Sprachabgleich, Preflight-Prüfungen und Ersetzen in einem Durchgang — kein Drag-and-drop im Browser.",
      "Füge Rechtecke, Kreise, Sterne, Text, Bilder und SVGs hinzu — und passe dann Größe, Drehung und Stil jedes Elements an. Lege Füllfarben, Verläufe, Deckkraft, Konturen und Eckenradius direkt im Inspektor fest. Staple Ebenen, zieh mit gedrückter Shift-Taste, um das Seitenverhältnis zu fixieren, und richte alles pixelgenau per Einrasten aus.",
      "Wähle aus 16 Verlaufsvorlagen, bau dir mit dem Multi-Stop-Editor eigene Verläufe oder setze Bilder mit den Modi Füllen, Einpassen, Strecken und Kacheln ein. Hintergründe können sich über mehrere Templates einer Zeile erstrecken — für nahtlose Designs von Kante zu Kante. Passe Winkel, Deckkraft und Farbstopps an — alles aktualisiert sich live.",
      "Wähle aus einer Bibliothek von Geräterahmen — iPhone, iPad, MacBook, iMac sowie Android-Smartphones und -Tablets. Tausche Rahmen, wähle Gehäusefarben und triff den Look deiner Marke, ohne Screenshots neu zu importieren.",
      "Schalte den lokalen MCP-Server ein, und Claude Code, Claude Desktop oder Cursor können Screenshot Bro steuern: ein Projekt anlegen, Zeilen und Formen anordnen, Screenshots importieren, Texte übersetzen, gerenderte Vorschauen ansehen, exportieren und das Set mit App Store Connect synchronisieren. Er lauscht nur auf 127.0.0.1, braucht ein Token aus den Einstellungen, und jede Änderung lässt sich mit ⌘Z rückgängig machen.",
    ],
    workflow: [
      "Wähle deine Gerätegrößen — iPhone, iPad, Mac oder Android-Smartphone und -Tablet, jeweils auf die Pixelmaße voreingestellt, die der jeweilige Store erwartet. Füge so viele Zeilen hinzu, wie du brauchst.",
      "Füge Geräterahmen, Text und Formen ein und wähle einen Hintergrund. Ergänze Sprachen, übersetze fehlende Texte automatisch und feile an den Textanpassungen pro Form, damit jede Sprache pixelgenau bleibt.",
      "Auf Exportieren klicken. Du bekommst Ordner, sortiert nach Sprache und Zeile, jeder Screenshot in genau der Größe, die der Store erwartet. Ein Klick.",
      "Verbinde deinen API-Schlüssel einmal und schick Screenshots direkt an die richtige App, Version, den richtigen Anzeigetyp und die richtige Sprache — ohne manuelles Drag-and-drop im Browser.",
    ],
  },
  ja: {
    features: {
      templates: "一度の編集で、すべてのバリエーションに反映。図形やテキストを変更すると、すべてのスクリーンショットに同時に適用されます。",
      project: "英語からアラビア語、ヒンディー語、CJKまで、81言語のプリセットを用意。足りない文言を自動翻訳したら、図形ごとにテキスト、位置、画像の上書きを微調整できます。翻訳の進捗も確認可能です。",
      export: "各行の正確なピクセルサイズで、PNGまたはJPEGをすべてのロケール分まとめて書き出し。フォルダはロケールと行ごとに自動で整理され、App Store Connect、Google Play、ローンチ用素材にそのまま使えます。",
      cloud: "オプションのiCloud Drive同期で、プロジェクトをMac、iPad、iPhoneのどこからでも利用できます。最後の書き込みを優先するマージと、削除済み項目（トゥームストーン）を考慮した競合解決に対応しています。",
      native: "SwiftとSwiftUIでMac、iPad、iPhone向けに開発。Electronでもブラウザのタブでもありません。瞬時に起動し、ネイティブの性能、自動保存、完全な取り消し/やり直しに対応しています。",
      fonts: "手持ちの.ttf、.otf、.ttcフォントファイルを読み込めます。テキスト図形にはどんな書体でも使用でき、システムフォントの制約はありません。",
      privacy: "自動翻訳はAppleのTranslationフレームワークを通じてデバイス上で実行されます。APIキー不要、アカウント不要、広告トラッキングなし。プロジェクト、フォント、スクリーンショットはデバイスの中にとどまります。",
      free: "1プロジェクト、3行、1行あたり5テンプレート。すべてのデバイスフレーム、81のロケールすべて、すべての書き出し形式を利用できます。透かしなし、試用期限なし、登録不要。",
    },
    showcases: [
      "複数のスクリーンショットをまとめてドラッグ＆ドロップ。Screenshot Broがすべてを読み込み、それぞれを自動でデバイスフレームに収めます。手作業での配置も、1枚ずつの面倒な作業も不要です。",
      "App Store Connect APIキーを一度接続すれば、レンダリングしたスクリーンショットを正しいアプリ、バージョン、表示タイプ、ロケールへ直接送信できます。表示タイプの自動検出、ロケールの照合、事前チェック、一括置き換えに対応。ブラウザでのドラッグ＆ドロップは不要です。",
      "長方形、円、星、テキスト、画像、SVGを追加し、それぞれのサイズ変更、回転、スタイル設定ができます。塗りの色、グラデーション、不透明度、輪郭線、角丸の半径もインスペクタから直接設定可能。レイヤーを重ね、Shiftキーを押しながらドラッグして縦横比を固定し、スナップでピクセル単位までぴったり整列できます。",
      "16種類のグラデーションプリセットから選ぶか、マルチストップエディタで独自のグラデーションを作成。画像を配置して、塗りつぶし、フィット、引き伸ばし、タイルの各モードも使えます。背景は行内の複数テンプレートにまたがって配置でき、端から端まで途切れのないデザインに。角度、不透明度、カラーストップを調整すると、すべてリアルタイムで更新されます。",
      "iPhone、iPad、MacBook、iMac、Androidスマートフォンとタブレットのデバイスベゼルをライブラリから選択。スクリーンショットを読み込み直すことなく、フレームを切り替え、本体カラーを選び、ブランドに合わせられます。",
      "ローカルMCPサーバーをオンにすると、Claude Code、Claude Desktop、CursorがScreenshot Broを操作できます。プロジェクトの作成、行と図形のレイアウト、スクリーンショットの読み込み、文言の翻訳、レンダリングしたプレビューの確認、書き出し、App Store Connectへのセットの同期まで。待ち受けは127.0.0.1のみで、設定画面のトークンが必要です。すべての変更は⌘Zで取り消せます。",
    ],
    workflow: [
      "デバイスサイズを選択。iPhone、iPad、Mac、Androidスマートフォンとタブレットは、それぞれのストアが求めるピクセルサイズにプリセット済みです。行は必要なだけ追加できます。",
      "デバイスフレームを配置し、テキストと図形を追加して、背景を選択。ロケールを追加して足りない文言を自動翻訳し、図形ごとのテキスト上書きを調整すれば、どの言語でもピクセル単位で完璧に仕上がります。",
      "書き出しを押すだけ。ロケールと行ごとに整理されたフォルダに、ストアが求める正確なサイズのスクリーンショットがそろいます。ワンクリックで完了。",
      "APIキーを一度接続すれば、スクリーンショットを正しいアプリ、バージョン、表示タイプ、ロケールへ直接送信。ブラウザへの手動ドラッグ＆ドロップは不要です。",
    ],
  },
  pt: {
    features: {
      templates: "Edite uma vez e atualize todas as variações. Altere uma forma ou um texto e a mudança se aplica a todas as suas capturas ao mesmo tempo.",
      project: "81 idiomas predefinidos, do inglês ao árabe, hindi e CJK. Traduza automaticamente os textos que faltam e depois ajuste por forma o texto, a posição e as imagens, acompanhando o progresso da tradução.",
      export: "Exporte em PNG ou JPEG no tamanho exato em pixels de cada linha, para todos os idiomas de uma vez. Pastas organizadas automaticamente por idioma e linha para App Store Connect, Google Play e materiais de lançamento.",
      cloud: "A sincronização opcional pelo iCloud Drive mantém seus projetos disponíveis em todos os seus Macs, iPads e iPhones. Mesclagem em que a última gravação prevalece, com resolução de conflitos que leva em conta itens excluídos.",
      native: "Feito com Swift e SwiftUI para Mac, iPad e iPhone. Sem Electron, sem aba de navegador. Abertura instantânea, desempenho nativo, salvamento automático e desfazer/refazer completo.",
      fonts: "Importe seus próprios arquivos de fonte .ttf, .otf ou .ttc. Use qualquer tipografia nas formas de texto — sem ficar limitado às fontes do sistema.",
      privacy: "A tradução automática roda no próprio dispositivo pelo framework Translation da Apple. Sem chaves de API, sem contas, sem rastreamento de anúncios — projetos, fontes e capturas ficam no seu dispositivo.",
      free: "1 projeto, 3 linhas, 5 modelos por linha — com todas as molduras de dispositivos, todos os 81 idiomas e todos os formatos de exportação. Sem marca d'água, sem teste que expira, sem cadastro.",
    },
    showcases: [
      "Arraste e solte várias capturas de uma vez — o Screenshot Bro importa todas e coloca cada uma automaticamente na moldura do dispositivo. Sem posicionamento manual, sem aquele trabalho cansativo de uma por uma.",
      "Conecte sua chave de API do App Store Connect uma única vez e envie as capturas renderizadas direto para o app, a versão, o tipo de tela e o idioma certos. Tipos de tela detectados automaticamente, correspondência de idiomas, verificações prévias e substituição em uma só passada — sem arrastar e soltar no navegador.",
      "Adicione retângulos, círculos, estrelas, textos, imagens e SVGs — depois redimensione, gire e estilize cada um. Defina cores de preenchimento, gradientes, opacidade, contornos e raio dos cantos direto no inspetor. Empilhe camadas, arraste com Shift para travar a proporção e alinhe tudo com precisão de pixel usando o encaixe automático.",
      "Escolha entre 16 gradientes predefinidos, crie o seu com o editor de múltiplas paradas ou use imagens nos modos preencher, ajustar, esticar e lado a lado. Os fundos podem se estender por vários modelos de uma linha para designs contínuos, de ponta a ponta. Ajuste o ângulo, a opacidade e as paradas de cor — tudo se atualiza ao vivo.",
      "Escolha em uma biblioteca de molduras de dispositivos — iPhone, iPad, MacBook, iMac e celulares e tablets Android. Troque molduras, escolha a cor do corpo e combine com a sua marca sem reimportar as capturas.",
      "Ative o servidor MCP local e o Claude Code, o Claude Desktop ou o Cursor podem controlar o Screenshot Bro: criar um projeto, organizar linhas e formas, importar capturas, traduzir textos, conferir as prévias renderizadas, exportar e sincronizar o conjunto com o App Store Connect. Ele escuta apenas em 127.0.0.1, exige um token dos Ajustes e toda alteração pode ser desfeita com ⌘Z.",
    ],
    workflow: [
      "Escolha os tamanhos de dispositivo — iPhone, iPad, Mac ou celular e tablet Android, cada um predefinido com os pixels que a sua loja exige. Adicione quantas linhas precisar.",
      "Coloque molduras de dispositivos, adicione textos e formas e escolha um fundo. Adicione idiomas, traduza automaticamente os textos que faltam e ajuste o texto de cada forma para que todos os idiomas fiquem perfeitos até o pixel.",
      "Clique em exportar. Receba pastas organizadas por idioma e linha, com cada captura no tamanho exato que a loja exige. Com um clique.",
      "Conecte sua chave de API uma única vez e envie as capturas direto para o app, a versão, o tipo de tela e o idioma certos — sem arrastar e soltar manualmente no navegador.",
    ],
  },
  it: {
    features: {
      templates: "Modifica una volta, aggiorna ogni variante. Cambia una forma o un testo e la modifica si applica contemporaneamente a tutti i tuoi screenshot.",
      project: "81 lingue predefinite, dall'inglese all'arabo, all'hindi e al CJK. Traduci automaticamente i testi mancanti, poi rifinisci per ogni forma testo, posizione e immagini, monitorando l'avanzamento delle traduzioni.",
      export: "Esporta in PNG o JPEG alla dimensione esatta in pixel di ogni riga, per tutte le lingue in un colpo solo. Cartelle organizzate automaticamente per lingua e riga per App Store Connect, Google Play e materiali di lancio.",
      cloud: "La sincronizzazione facoltativa con iCloud Drive mantiene i tuoi progetti disponibili su tutti i tuoi Mac, iPad e iPhone. Unione secondo il criterio «vince l'ultima scrittura» e risoluzione dei conflitti che tiene conto degli elementi eliminati.",
      native: "Realizzata con Swift e SwiftUI per Mac, iPad e iPhone. Niente Electron, nessuna scheda del browser. Avvio istantaneo, prestazioni native, salvataggio automatico, annulla/ripristina completo.",
      fonts: "Importa i tuoi file di font .ttf, .otf o .ttc. Usa qualsiasi carattere nelle forme di testo — senza i limiti dei font di sistema.",
      privacy: "La traduzione automatica avviene sul dispositivo tramite il framework Translation di Apple. Niente chiavi API, niente account, nessun tracciamento pubblicitario — progetti, font e screenshot restano sul tuo dispositivo.",
      free: "1 progetto, 3 righe, 5 modelli per riga — con tutte le cornici dispositivo, tutte le 81 lingue e tutti i formati di export. Niente filigrana, nessuna prova a scadenza, nessuna registrazione.",
    },
    showcases: [
      "Trascina e rilascia più screenshot in una volta — Screenshot Bro li importa tutti e inserisce automaticamente ciascuno nella cornice del dispositivo. Niente posizionamento manuale, niente noioso lavoro uno alla volta.",
      "Collega una sola volta la tua chiave API di App Store Connect, poi invia gli screenshot renderizzati direttamente all'app, alla versione, al tipo di display e alla lingua giusti. Tipi di display rilevati automaticamente, abbinamento delle lingue, controlli preliminari e sostituzione in un solo passaggio — senza trascinare file nel browser.",
      "Aggiungi rettangoli, cerchi, stelle, testi, immagini e SVG — poi ridimensiona, ruota e personalizza lo stile di ciascuno. Imposta colori di riempimento, gradienti, opacità, contorni e raggio degli angoli direttamente dall'inspector. Sovrapponi i livelli, trascina con Maiusc per bloccare le proporzioni e allinea tutto al pixel con l'aggancio automatico.",
      "Scegli tra 16 gradienti predefiniti, creane uno tuo con l'editor multi-stop o inserisci immagini con le modalità riempi, adatta, estendi e affianca. Gli sfondi possono estendersi su più modelli di una riga per design continui, da bordo a bordo. Regola angolo, opacità e punti colore — tutto si aggiorna in tempo reale.",
      "Scegli da una libreria di cornici dispositivo — iPhone, iPad, MacBook, iMac e smartphone e tablet Android. Cambia cornice, scegli il colore della scocca e abbinala al tuo brand senza reimportare gli screenshot.",
      "Attiva il server MCP locale e Claude Code, Claude Desktop o Cursor possono pilotare Screenshot Bro: creare un progetto, disporre righe e forme, importare screenshot, tradurre i testi, esaminare le anteprime renderizzate, esportare e sincronizzare il set con App Store Connect. È in ascolto solo su 127.0.0.1, richiede un token dalle Impostazioni e ogni modifica si annulla con ⌘Z.",
    ],
    workflow: [
      "Scegli le dimensioni dei dispositivi — iPhone, iPad, Mac o smartphone e tablet Android, ciascuno preimpostato sui pixel richiesti dal suo store. Aggiungi tutte le righe che ti servono.",
      "Inserisci le cornici dispositivo, aggiungi testi e forme, scegli uno sfondo. Aggiungi le lingue, traduci automaticamente i testi mancanti e regola il testo di ogni forma perché ogni lingua resti perfetta al pixel.",
      "Premi esporta. Ottieni cartelle organizzate per lingua e riga, con ogni screenshot alla dimensione esatta richiesta dallo store. Un solo clic.",
      "Collega una sola volta la tua chiave API, poi invia gli screenshot direttamente all'app, alla versione, al tipo di display e alla lingua giusti — senza trascinare a mano i file nel browser.",
    ],
  },
  uk: {
    features: {
      templates: "Редагуйте один раз — оновлюйте всі варіанти. Змініть фігуру чи текст, і зміни одночасно з'являться на всіх ваших скриншотах.",
      project: "81 попередньо налаштована мова — від англійської до арабської, гінді та CJK. Автоматично перекладайте відсутній текст, а потім точно налаштовуйте текст, позицію та зображення для кожної фігури, відстежуючи прогрес перекладу.",
      export: "Експортуйте PNG або JPEG точно в піксельному розмірі кожного рядка — одразу для всіх мов. Файли автоматично розкладаються по папках за мовою та рядком для App Store Connect, Google Play і матеріалів до запуску.",
      cloud: "Опціональна синхронізація через iCloud Drive робить проекти доступними на всіх ваших Mac, iPad та iPhone. Злиття за правилом останньої зміни (last-writer-wins) і вирішення конфліктів з урахуванням видалених елементів.",
      native: "Створено на Swift і SwiftUI для Mac, iPad та iPhone. Жодного Electron, жодної вкладки браузера. Миттєвий запуск, нативна швидкодія, автозбереження, повне скасування та повторення дій.",
      fonts: "Імпортуйте власні файли шрифтів .ttf, .otf або .ttc. Використовуйте будь-яку гарнітуру в текстових фігурах — без обмежень системних шрифтів.",
      privacy: "Автопереклад виконується прямо на пристрої через фреймворк Apple Translation. Жодних API-ключів, облікових записів чи рекламного стеження — проекти, шрифти та скриншоти залишаються на вашому пристрої.",
      free: "1 проект, 3 рядки, 5 шаблонів на рядок — з усіма рамками пристроїв, усіма 81 мовами та всіма форматами експорту. Без водяних знаків, без завершення пробного періоду, без реєстрації.",
    },
    showcases: [
      "Перетягніть одразу кілька скриншотів — Screenshot Bro імпортує їх усі й автоматично вставить кожен у рамку пристрою. Жодного ручного розміщення, жодної нудної роботи з кожним файлом окремо.",
      "Підключіть API-ключ App Store Connect один раз — і надсилайте відрендерені скриншоти прямо до потрібного додатку, версії, типу дисплея та мови. Автовизначення типів дисплея, зіставлення мов, попередні перевірки та заміна за один прохід — без перетягування файлів у браузері.",
      "Додавайте прямокутники, кола, зірки, текст, зображення та SVG — а потім змінюйте розмір, обертайте й стилізуйте кожен елемент. Налаштовуйте кольори заливки, градієнти, прозорість, обведення та радіус кутів прямо в інспекторі. Розташовуйте шари один над одним, фіксуйте пропорції перетягуванням із Shift і вирівнюйте елементи з точністю до пікселя завдяки прив'язці.",
      "Оберіть один із 16 готових градієнтів, створіть власний у редакторі з кількома точками кольору або додайте зображення з режимами заповнення, вписування, розтягування та мозаїки. Фони можуть розтягуватися на кілька шаблонів у рядку для безшовного дизайну від краю до краю. Налаштовуйте кут, прозорість і точки кольору — усе оновлюється в реальному часі.",
      "Обирайте з бібліотеки рамок пристроїв — iPhone, iPad, MacBook, iMac, а також телефони й планшети Android. Змінюйте рамки, обирайте колір корпусу та підлаштовуйте все під свій бренд без повторного імпорту скриншотів.",
      "Увімкніть локальний MCP-сервер — і Claude Code, Claude Desktop або Cursor зможуть керувати Screenshot Bro: створювати проект, розміщувати рядки та фігури, імпортувати скриншоти, перекладати текст, переглядати відрендерені прев'ю, експортувати й синхронізувати набір з App Store Connect. Сервер слухає лише 127.0.0.1, потребує токена з Налаштувань, а кожну зміну можна скасувати через ⌘Z.",
    ],
    workflow: [
      "Оберіть розміри пристроїв — iPhone, iPad, Mac або телефон і планшет Android; кожен уже налаштований під піксельні розміри, яких вимагає відповідний магазин. Додавайте стільки рядків, скільки потрібно.",
      "Додайте рамки пристроїв, текст і фігури, оберіть фон. Додайте мови, автоматично перекладіть відсутній текст і налаштуйте перевизначення тексту для окремих фігур, щоб кожна мова виглядала бездоганно до пікселя.",
      "Натисніть «Експорт». Отримайте впорядковані папки за мовами та рядками — кожен скриншот точно в тому розмірі, якого вимагає магазин. Один клік.",
      "Підключіть API-ключ один раз — і надсилайте скриншоти прямо до потрібного додатку, версії, типу дисплея та мови, без ручного перетягування файлів у браузер.",
    ],
  },
  pl: {
    features: {
      templates: "Edytujesz raz, aktualizujesz każdy wariant. Zmień kształt lub tekst, a zmiana pojawi się jednocześnie na wszystkich Twoich zrzutach ekranu.",
      project: "81 gotowych ustawień językowych — od angielskiego po arabski, hindi i języki CJK. Automatycznie tłumacz brakujące teksty, a potem dopracuj tekst, położenie i obrazy dla każdego kształtu, śledząc postęp tłumaczenia.",
      export: "Eksportuj PNG lub JPEG w dokładnym rozmiarze w pikselach każdego wiersza, dla wszystkich języków naraz. Pliki trafiają automatycznie do folderów według języka i wiersza — gotowe dla App Store Connect, Google Play i materiałów na premierę.",
      cloud: "Opcjonalna synchronizacja przez iCloud Drive udostępnia projekty na wszystkich Twoich Macach, iPadach i iPhone'ach. Scalanie według zasady „wygrywa ostatni zapis” z rozwiązywaniem konfliktów, które uwzględnia usunięte elementy.",
      native: "Zbudowana w Swift i SwiftUI na Maca, iPada i iPhone'a. Bez Electron i bez karty przeglądarki. Błyskawiczne uruchamianie, natywna wydajność, automatyczny zapis, pełne cofanie i ponawianie.",
      fonts: "Importuj własne pliki czcionek .ttf, .otf lub .ttc. Używaj dowolnego kroju w kształtach tekstowych — bez ograniczeń czcionek systemowych.",
      privacy: "Automatyczne tłumaczenie działa na urządzeniu dzięki frameworkowi Apple Translation. Bez kluczy API, kont i śledzenia reklamowego — projekty, czcionki i zrzuty ekranu zostają na Twoim urządzeniu.",
      free: "1 projekt, 3 wiersze, 5 szablonów na wiersz — ze wszystkimi ramkami urządzeń, wszystkimi 81 językami i każdym formatem eksportu. Bez znaku wodnego, bez wygasającego okresu próbnego, bez rejestracji.",
    },
    showcases: [
      "Przeciągnij i upuść kilka zrzutów ekranu naraz — Screenshot Bro zaimportuje je wszystkie i automatycznie umieści każdy w ramce urządzenia. Bez ręcznego układania i żmudnej pracy plik po pliku.",
      "Podłącz klucz API App Store Connect raz, a potem wysyłaj wyrenderowane zrzuty ekranu prosto do właściwej aplikacji, wersji, typu wyświetlacza i języka. Automatyczne wykrywanie typów wyświetlaczy, dopasowanie języków, kontrole wstępne i zastępowanie w jednym przebiegu — bez przeciągania plików w przeglądarce.",
      "Dodawaj prostokąty, koła, gwiazdy, tekst, obrazy i SVG — a potem zmieniaj ich rozmiar, obracaj je i stylizuj. Ustawiaj kolory wypełnienia, gradienty, krycie, obrysy i zaokrąglenie narożników bezpośrednio w inspektorze. Układaj warstwy, przeciągaj z Shift, aby zablokować proporcje, i przyciągaj elementy z dokładnością do piksela.",
      "Wybierz jeden z 16 gotowych gradientów, stwórz własny w edytorze z wieloma punktami koloru albo dodaj obrazy w trybach wypełnienia, dopasowania, rozciągnięcia i kafelkowania. Tła mogą rozciągać się na kilka szablonów w wierszu, tworząc płynne projekty od krawędzi do krawędzi. Dostosuj kąt, krycie i punkty koloru — wszystko aktualizuje się na żywo.",
      "Wybieraj z biblioteki ramek urządzeń — iPhone, iPad, MacBook, iMac oraz telefony i tablety z Androidem. Zamieniaj ramki, wybieraj kolory obudowy i dopasuj wszystko do swojej marki bez ponownego importowania zrzutów ekranu.",
      "Włącz lokalny serwer MCP, a Claude Code, Claude Desktop lub Cursor przejmie sterowanie Screenshot Bro: utworzy projekt, ułoży wiersze i kształty, zaimportuje zrzuty ekranu, przetłumaczy teksty, obejrzy wyrenderowane podglądy, wyeksportuje i zsynchronizuje zestaw z App Store Connect. Serwer nasłuchuje tylko na 127.0.0.1, wymaga tokenu z Ustawień, a każdą zmianę cofniesz za pomocą ⌘Z.",
    ],
    workflow: [
      "Wybierz rozmiary urządzeń — iPhone, iPad, Mac albo telefon i tablet z Androidem, każdy z rozdzielczością wymaganą przez swój sklep. Dodaj tyle wierszy, ile potrzebujesz.",
      "Wstaw ramki urządzeń, dodaj tekst i kształty, wybierz tło. Dodaj języki, automatycznie przetłumacz brakujące teksty i dopracuj nadpisania tekstu dla poszczególnych kształtów, aby każdy język wyglądał idealnie co do piksela.",
      "Kliknij eksport. Otrzymasz uporządkowane foldery według języka i wiersza, a każdy zrzut ekranu w dokładnie takim rozmiarze, jakiego wymaga sklep. Jedno kliknięcie.",
      "Podłącz klucz API raz, a potem wysyłaj zrzuty ekranu prosto do właściwej aplikacji, wersji, typu wyświetlacza i języka — bez ręcznego przeciągania plików do przeglądarki.",
    ],
  },
  tr: {
    features: {
      templates: "Bir kez düzenleyin, tüm varyantları güncelleyin. Bir şekli veya metni değiştirdiğinizde değişiklik tüm ekran görüntülerinize aynı anda yansır.",
      project: "İngilizceden Arapça, Hintçe ve CJK dillerine kadar 81 dil ön ayarı. Eksik metinleri otomatik çevirin, ardından çeviri ilerlemesini takip ederek her şekil için metin, konum ve görsel geçersiz kılmalarına ince ayar yapın.",
      export: "PNG veya JPEG dosyalarını her satırın tam piksel boyutunda, tüm diller için tek seferde dışa aktarın. App Store Connect, Google Play ve lansman materyalleri için dile ve satıra göre otomatik düzenlenen klasörler.",
      cloud: "İsteğe bağlı iCloud Drive eşzamanlaması, projelerinizi tüm Mac, iPad ve iPhone cihazlarınızda erişilebilir tutar. Çakışmalar, silinen öğeleri de hesaba katan \"son yazan kazanır\" birleştirmesiyle çözülür.",
      native: "Mac, iPad ve iPhone için Swift ve SwiftUI ile geliştirildi. Electron yok, tarayıcı sekmesi yok. Anında açılış, yerel performans, otomatik kaydetme, tam geri al/yinele.",
      fonts: "Kendi .ttf, .otf veya .ttc yazı tipi dosyalarınızı içe aktarın. Metin şekillerinde istediğiniz yazı tipini kullanın — sistem yazı tiplerinin sınırlamaları olmadan.",
      privacy: "Otomatik çeviri, Apple'ın Translation çerçevesiyle cihaz üzerinde çalışır. API anahtarı yok, hesap yok, reklam takibi yok — projeler, yazı tipleri ve ekran görüntüleri cihazınızda kalır.",
      free: "1 proje, 3 satır, satır başına 5 şablon — tüm cihaz çerçeveleri, 81 dilin tamamı ve her dışa aktarma biçimiyle. Filigran yok, deneme süresi dolmuyor, kayıt gerekmiyor.",
    },
    showcases: [
      "Birden fazla ekran görüntüsünü aynı anda sürükleyip bırakın — Screenshot Bro hepsini içe aktarır ve her birini otomatik olarak cihaz çerçevesine yerleştirir. Elle yerleştirme yok, tek tek uğraşmak yok.",
      "App Store Connect API anahtarınızı bir kez bağlayın, ardından oluşturulan ekran görüntülerini doğrudan doğru uygulamaya, sürüme, ekran türüne ve dile gönderin. Otomatik algılanan ekran türleri, dil eşleştirme, ön kontroller ve tek geçişte değiştirme — tarayıcıda sürükle-bırak yok.",
      "Dikdörtgenler, daireler, yıldızlar, metin, görseller ve SVG'ler ekleyin; ardından her birini yeniden boyutlandırın, döndürün ve biçimlendirin. Dolgu renklerini, degradeleri, opaklığı, kenar çizgilerini ve köşe yarıçapını doğrudan denetçiden ayarlayın. Katmanları üst üste dizin, en-boy oranını kilitlemek için Shift ile sürükleyin ve piksel hassasiyetinde hizalamak için yapışmayı kullanın.",
      "16 hazır degrade arasından seçim yapın, çok duraklı düzenleyiciyle kendinizinkini oluşturun veya doldurma, sığdırma, uzatma ve döşeme modlarıyla görseller ekleyin. Arka planlar, kesintisiz ve kenardan kenara tasarımlar için bir satırdaki birden fazla şablona yayılabilir. Açıyı, opaklığı ve renk duraklarını ayarlayın — her şey anında güncellenir.",
      "Cihaz çerçevesi kütüphanesinden seçin — iPhone, iPad, MacBook, iMac ve Android telefon ve tabletler. Ekran görüntülerini yeniden içe aktarmadan çerçeveleri değiştirin, gövde renklerini seçin ve markanıza uyum sağlayın.",
      "Yerel MCP sunucusunu açın; Claude Code, Claude Desktop veya Cursor Screenshot Bro'yu yönetebilsin: proje oluşturma, satırları ve şekilleri yerleştirme, ekran görüntülerini içe aktarma, metinleri çevirme, oluşturulan önizlemelere bakma, dışa aktarma ve seti App Store Connect ile eşzamanlama. Sunucu yalnızca 127.0.0.1 üzerinde dinler, Ayarlar'dan alınan bir token gerektirir ve her değişiklik ⌘Z ile geri alınabilir.",
    ],
    workflow: [
      "Cihaz boyutlarınızı seçin — iPhone, iPad, Mac ya da Android telefon ve tablet; her biri ilgili mağazanın beklediği piksel boyutlarına önceden ayarlıdır. İhtiyacınız kadar satır ekleyin.",
      "Cihaz çerçevelerini yerleştirin, metin ve şekiller ekleyin, bir arka plan seçin. Dilleri ekleyin, eksik metinleri otomatik çevirin ve her dilin piksel piksel kusursuz kalması için şekil bazında metin geçersiz kılmalarını ayarlayın.",
      "Dışa aktar'a basın. Dile ve satıra göre düzenlenmiş klasörler elde edin; her ekran görüntüsü mağazanın beklediği tam boyutta. Tek tık.",
      "API anahtarınızı bir kez bağlayın, ardından ekran görüntülerini doğrudan doğru uygulamaya, sürüme, ekran türüne ve dile gönderin — tarayıcıya elle sürükle-bırak yok.",
    ],
  },
  nl: {
    features: {
      templates: "Eén keer bewerken, elke variant bijgewerkt. Pas een vorm of tekst aan en de wijziging verschijnt tegelijk in al je screenshots.",
      project: "81 taalpresets, van Engels tot Arabisch, Hindi en CJK. Vertaal ontbrekende teksten automatisch en verfijn daarna per vorm de tekst, positie en afbeeldingen, terwijl je de voortgang van de vertalingen bijhoudt.",
      export: "Exporteer PNG of JPEG op het exacte pixelformaat van elke rij, voor alle talen tegelijk. Automatisch geordende mappen per taal en rij voor App Store Connect, Google Play en lanceermateriaal.",
      cloud: "Optionele iCloud Drive-synchronisatie houdt je projecten beschikbaar op al je Macs, iPads en iPhones. Samenvoegen volgens 'laatste schrijver wint', met conflictoplossing die rekening houdt met verwijderde items.",
      native: "Gebouwd met Swift en SwiftUI voor Mac, iPad en iPhone. Geen Electron, geen browsertabblad. Direct opstarten, native prestaties, automatisch opslaan, volledig ongedaan maken en opnieuw uitvoeren.",
      fonts: "Importeer je eigen .ttf-, .otf- of .ttc-lettertypebestanden. Gebruik elk gewenst lettertype in tekstvormen — zonder de beperkingen van systeemlettertypen.",
      privacy: "Automatisch vertalen gebeurt op het apparaat via het Translation-framework van Apple. Geen API-sleutels, geen accounts, geen advertentietracking — projecten, lettertypen en screenshots blijven op je apparaat.",
      free: "1 project, 3 rijen, 5 sjablonen per rij — met elk apparaatframe, alle 81 talen en elk exportformaat. Geen watermerk, geen proefperiode die afloopt, geen registratie.",
    },
    showcases: [
      "Sleep meerdere screenshots tegelijk naar binnen — Screenshot Bro importeert ze allemaal en plaatst elk automatisch in het apparaatframe. Geen handmatig plaatsen, geen eindeloos één-voor-één-werk.",
      "Koppel je App Store Connect API-sleutel één keer en stuur gerenderde screenshots direct naar de juiste app, versie, schermtype en taal. Automatisch herkende schermtypen, taalkoppeling, controles vooraf en vervangen in één keer — geen slepen en neerzetten in de browser.",
      "Voeg rechthoeken, cirkels, sterren, tekst, afbeeldingen en SVG's toe — en schaal, roteer en style ze daarna stuk voor stuk. Stel vulkleuren, verlopen, dekking, omlijningen en hoekradius direct in de inspector in. Stapel lagen, sleep met Shift om de beeldverhouding vast te zetten en lijn alles pixelperfect uit met snapping.",
      "Kies uit 16 verloop-presets, maak je eigen verloop met de editor voor meerdere kleurstops of voeg afbeeldingen toe met de modi vullen, passend maken, uitrekken en tegelen. Achtergronden kunnen meerdere sjablonen in een rij overspannen voor naadloze ontwerpen van rand tot rand. Pas hoek, dekking en kleurstops aan — alles wordt live bijgewerkt.",
      "Kies uit een bibliotheek met apparaatframes — iPhone, iPad, MacBook, iMac en Android-telefoons en -tablets. Wissel van frame, kies de kleur van de behuizing en stem alles af op je merk zonder screenshots opnieuw te importeren.",
      "Zet de lokale MCP-server aan en Claude Code, Claude Desktop of Cursor kan Screenshot Bro besturen: een project maken, rijen en vormen opzetten, screenshots importeren, teksten vertalen, gerenderde voorbeelden bekijken, exporteren en de set synchroniseren met App Store Connect. De server luistert alleen op 127.0.0.1, vereist een token uit Instellingen en elke wijziging maak je ongedaan met ⌘Z.",
    ],
    workflow: [
      "Kies je apparaatformaten — iPhone, iPad, Mac of Android-telefoon en -tablet, elk vooraf ingesteld op de pixels die de bijbehorende store verwacht. Voeg zoveel rijen toe als je nodig hebt.",
      "Plaats apparaatframes, voeg tekst en vormen toe en kies een achtergrond. Voeg talen toe, vertaal ontbrekende teksten automatisch en verfijn tekstoverschrijvingen per vorm, zodat elke taal pixelperfect blijft.",
      "Klik op exporteren. Je krijgt mappen geordend per taal en rij, met elke screenshot op precies het formaat dat de store verwacht. Eén klik.",
      "Koppel je API-sleutel één keer en stuur screenshots direct naar de juiste app, versie, schermtype en taal — zonder handmatig slepen en neerzetten in de browser.",
    ],
  },
  id: {
    features: {
      templates: "Edit sekali, semua varian ikut diperbarui. Ubah bentuk atau teks, dan perubahannya langsung diterapkan ke semua tangkapan layar Anda sekaligus.",
      project: "81 preset bahasa, dari Inggris hingga Arab, Hindi, dan CJK. Terjemahkan teks yang belum ada secara otomatis, lalu sempurnakan teks, posisi, dan gambar per bentuk sambil memantau progres terjemahan.",
      export: "Ekspor PNG atau JPEG dengan ukuran piksel persis setiap baris, untuk semua bahasa sekaligus. Folder tertata otomatis per bahasa dan baris untuk App Store Connect, Google Play, dan aset peluncuran.",
      cloud: "Sinkronisasi iCloud Drive opsional membuat proyek tetap tersedia di semua Mac, iPad, dan iPhone Anda. Penggabungan last-writer-wins dengan resolusi konflik yang memperhitungkan item yang telah dihapus.",
      native: "Dibuat dengan Swift dan SwiftUI untuk Mac, iPad, dan iPhone. Tanpa Electron, tanpa tab browser. Terbuka seketika, performa native, simpan otomatis, undo/redo penuh.",
      fonts: "Impor file font .ttf, .otf, atau .ttc milik Anda sendiri. Gunakan typeface apa pun di bentuk teks — tanpa batasan font sistem.",
      privacy: "Terjemahan otomatis berjalan di perangkat melalui framework Translation dari Apple. Tanpa kunci API, tanpa akun, tanpa pelacakan iklan — proyek, font, dan tangkapan layar tetap berada di perangkat Anda.",
      free: "1 proyek, 3 baris, 5 template per baris — dengan semua bingkai perangkat, ke-81 bahasa, dan semua format ekspor. Tanpa watermark, tanpa masa uji coba yang berakhir, tanpa pendaftaran.",
    },
    showcases: [
      "Tarik dan lepas beberapa tangkapan layar sekaligus — Screenshot Bro mengimpor semuanya dan otomatis memasukkan masing-masing ke dalam bingkai perangkat. Tanpa penempatan manual, tanpa proses satu per satu yang melelahkan.",
      "Hubungkan kunci API App Store Connect Anda sekali, lalu kirim tangkapan layar hasil render langsung ke aplikasi, versi, jenis layar, dan bahasa yang tepat. Deteksi otomatis jenis layar, pencocokan bahasa, pemeriksaan awal, dan penggantian dalam satu kali proses — tanpa tarik-lepas di browser.",
      "Tambahkan persegi panjang, lingkaran, bintang, teks, gambar, dan SVG — lalu ubah ukuran, putar, dan atur gaya masing-masing. Atur warna isian, gradien, opasitas, garis tepi, dan radius sudut langsung dari inspector. Tumpuk lapisan, seret sambil menahan Shift untuk mengunci rasio aspek, dan gunakan snap untuk perataan yang presisi hingga piksel.",
      "Pilih dari 16 preset gradien, buat sendiri dengan editor multi-stop, atau masukkan gambar dengan mode isi, pas, regang, dan ubin. Latar belakang dapat membentang di beberapa template dalam satu baris untuk desain mulus dari tepi ke tepi. Atur sudut, opasitas, dan titik warna — semuanya diperbarui secara langsung.",
      "Pilih dari pustaka bingkai perangkat — iPhone, iPad, MacBook, iMac, serta ponsel & tablet Android. Ganti bingkai, pilih warna bodi, dan sesuaikan dengan merek Anda tanpa mengimpor ulang tangkapan layar.",
      "Aktifkan server MCP lokal, dan Claude Code, Claude Desktop, atau Cursor dapat mengendalikan Screenshot Bro: membuat proyek, menata baris dan bentuk, mengimpor tangkapan layar, menerjemahkan teks, melihat pratinjau hasil render, mengekspor, dan menyinkronkan set ke App Store Connect. Server hanya mendengarkan di 127.0.0.1, memerlukan token dari Pengaturan, dan setiap perubahan bisa dibatalkan dengan ⌘Z.",
    ],
    workflow: [
      "Pilih ukuran perangkat Anda — iPhone, iPad, Mac, atau ponsel dan tablet Android, masing-masing sudah diatur ke ukuran piksel yang diminta tokonya. Tambahkan baris sebanyak yang Anda perlukan.",
      "Masukkan bingkai perangkat, tambahkan teks dan bentuk, pilih latar belakang. Tambahkan bahasa, terjemahkan otomatis teks yang belum ada, dan sesuaikan penggantian teks per bentuk agar setiap bahasa tetap sempurna hingga piksel.",
      "Tekan ekspor. Dapatkan folder yang tertata per bahasa dan baris, dengan setiap tangkapan layar berukuran persis seperti yang diminta toko. Satu klik.",
      "Hubungkan kunci API Anda sekali, lalu kirim tangkapan layar langsung ke aplikasi, versi, jenis layar, dan bahasa yang tepat — tanpa tarik-lepas manual ke browser.",
    ],
  },
  vi: {
    features: {
      templates: "Chỉnh sửa một lần, cập nhật mọi biến thể. Thay đổi một hình dạng hoặc văn bản và thay đổi sẽ được áp dụng đồng thời cho tất cả ảnh chụp màn hình của bạn.",
      project: "81 ngôn ngữ thiết lập sẵn, từ tiếng Anh đến tiếng Ả Rập, tiếng Hindi và CJK. Tự động dịch nội dung còn thiếu, sau đó tinh chỉnh văn bản, vị trí và hình ảnh cho từng hình dạng, kèm theo dõi tiến độ dịch.",
      export: "Xuất PNG hoặc JPEG đúng kích thước pixel của từng hàng, cho mọi ngôn ngữ cùng lúc. Thư mục được tự động sắp xếp theo ngôn ngữ và hàng cho App Store Connect, Google Play và tài nguyên ra mắt.",
      cloud: "Đồng bộ iCloud Drive tùy chọn giúp dự án luôn sẵn có trên mọi Mac, iPad và iPhone của bạn. Hợp nhất theo nguyên tắc bản ghi sau cùng thắng (last-writer-wins), xử lý xung đột có tính đến các mục đã xóa.",
      native: "Được xây dựng bằng Swift và SwiftUI cho Mac, iPad và iPhone. Không Electron, không tab trình duyệt. Khởi động tức thì, hiệu năng native, tự động lưu, hoàn tác/làm lại đầy đủ.",
      fonts: "Nhập tệp phông chữ .ttf, .otf hoặc .ttc của riêng bạn. Dùng bất kỳ kiểu chữ nào trong hình dạng văn bản — không bị giới hạn bởi phông chữ hệ thống.",
      privacy: "Tự động dịch chạy ngay trên thiết bị thông qua framework Translation của Apple. Không API key, không tài khoản, không theo dõi quảng cáo — dự án, phông chữ và ảnh chụp màn hình luôn nằm trên thiết bị của bạn.",
      free: "1 dự án, 3 hàng, 5 mẫu mỗi hàng — với mọi khung thiết bị, đủ 81 ngôn ngữ và mọi định dạng xuất. Không hình mờ, không hết hạn dùng thử, không cần đăng ký.",
    },
    showcases: [
      "Kéo và thả nhiều ảnh chụp màn hình cùng lúc — Screenshot Bro nhập tất cả và tự động đặt từng ảnh vào khung thiết bị. Không cần đặt thủ công, không phải làm từng ảnh một đầy tẻ nhạt.",
      "Kết nối API key App Store Connect một lần, sau đó đẩy ảnh chụp màn hình đã render thẳng đến đúng ứng dụng, phiên bản, loại màn hình và ngôn ngữ. Tự động nhận diện loại màn hình, khớp ngôn ngữ, kiểm tra trước và thay thế trong một lượt — không phải kéo thả trên trình duyệt.",
      "Thêm hình chữ nhật, hình tròn, ngôi sao, văn bản, hình ảnh và SVG — rồi thay đổi kích thước, xoay và tạo kiểu cho từng đối tượng. Đặt màu tô, gradient, độ mờ, viền và bo góc ngay trong inspector. Xếp chồng các lớp, giữ Shift khi kéo để khóa tỷ lệ khung hình và bắt dính để căn chỉnh chính xác đến từng pixel.",
      "Chọn từ 16 gradient có sẵn, tự tạo gradient với trình chỉnh sửa nhiều điểm màu, hoặc thêm hình ảnh với các chế độ lấp đầy, vừa khít, kéo giãn và lát gạch. Hình nền có thể trải rộng qua nhiều mẫu trong một hàng để tạo thiết kế liền mạch từ cạnh này sang cạnh kia. Điều chỉnh góc, độ mờ và điểm màu — mọi thứ cập nhật trực tiếp.",
      "Chọn từ thư viện khung thiết bị — iPhone, iPad, MacBook, iMac cùng điện thoại và máy tính bảng Android. Đổi khung, chọn màu thân máy và khớp với thương hiệu của bạn mà không cần nhập lại ảnh chụp màn hình.",
      "Bật máy chủ MCP cục bộ để Claude Code, Claude Desktop hoặc Cursor điều khiển Screenshot Bro: tạo dự án, bố trí hàng và hình dạng, nhập ảnh chụp màn hình, dịch nội dung, xem bản xem trước đã render, xuất file và đồng bộ bộ ảnh lên App Store Connect. Máy chủ chỉ lắng nghe trên 127.0.0.1, cần token từ phần Cài đặt và mọi thay đổi đều hoàn tác được bằng ⌘Z.",
    ],
    workflow: [
      "Chọn kích thước thiết bị — iPhone, iPad, Mac hoặc điện thoại và máy tính bảng Android, mỗi loại đã được thiết lập sẵn đúng số pixel mà cửa hàng tương ứng yêu cầu. Thêm bao nhiêu hàng tùy nhu cầu.",
      "Thêm khung thiết bị, văn bản và hình dạng, chọn hình nền. Thêm ngôn ngữ, tự động dịch nội dung còn thiếu và tinh chỉnh văn bản riêng cho từng hình dạng để mọi ngôn ngữ đều hoàn hảo đến từng pixel.",
      "Nhấn xuất. Nhận các thư mục được sắp xếp theo ngôn ngữ và hàng, mỗi ảnh chụp màn hình đúng kích thước cửa hàng yêu cầu. Chỉ một cú nhấp.",
      "Kết nối API key một lần, sau đó đẩy ảnh chụp màn hình thẳng đến đúng ứng dụng, phiên bản, loại màn hình và ngôn ngữ — không cần kéo thả thủ công vào trình duyệt.",
    ],
  },
  th: {
    features: {
      templates: "แก้ไขครั้งเดียว อัปเดตทุกเวอร์ชัน เปลี่ยนรูปทรงหรือข้อความ แล้วการเปลี่ยนแปลงจะมีผลกับสกรีนช็อตทั้งหมดของคุณพร้อมกัน",
      project: "ภาษาที่ตั้งค่าไว้ล่วงหน้า 81 ภาษา ตั้งแต่ภาษาอังกฤษไปจนถึงภาษาอาหรับ ฮินดี และ CJK แปลข้อความที่ขาดหายไปโดยอัตโนมัติ จากนั้นปรับแต่งข้อความ ตำแหน่ง และรูปภาพของแต่ละรูปทรง พร้อมติดตามความคืบหน้าการแปล",
      export: "ส่งออก PNG หรือ JPEG ตามขนาดพิกเซลที่แน่นอนของแต่ละแถว สำหรับทุกภาษาในครั้งเดียว จัดโฟลเดอร์ตามภาษาและแถวให้อัตโนมัติ สำหรับ App Store Connect, Google Play และสื่อสำหรับการเปิดตัว",
      cloud: "การซิงค์ผ่าน iCloud Drive แบบเลือกเปิดได้ ช่วยให้โปรเจกต์พร้อมใช้งานบน Mac, iPad และ iPhone ทุกเครื่องของคุณ รวมข้อมูลแบบผู้เขียนล่าสุดชนะ (last-writer-wins) พร้อมระบบแก้ไขความขัดแย้งที่คำนึงถึงรายการที่ถูกลบ",
      native: "สร้างด้วย Swift และ SwiftUI สำหรับ Mac, iPad และ iPhone ไม่ใช่ Electron ไม่ใช่แท็บเบราว์เซอร์ เปิดได้ทันที ประสิทธิภาพเนทีฟ บันทึกอัตโนมัติ เลิกทำ/ทำซ้ำได้เต็มรูปแบบ",
      fonts: "นำเข้าไฟล์ฟอนต์ .ttf, .otf หรือ .ttc ของคุณเอง ใช้แบบอักษรใดก็ได้ในรูปทรงข้อความ โดยไม่ถูกจำกัดด้วยฟอนต์ของระบบ",
      privacy: "การแปลอัตโนมัติทำงานบนอุปกรณ์ผ่านเฟรมเวิร์ก Translation ของ Apple ไม่ต้องใช้คีย์ API ไม่ต้องมีบัญชี ไม่มีการติดตามเพื่อโฆษณา โปรเจกต์ ฟอนต์ และสกรีนช็อตอยู่บนอุปกรณ์ของคุณ",
      free: "1 โปรเจกต์ 3 แถว 5 เทมเพลตต่อแถว พร้อมกรอบอุปกรณ์ทุกแบบ ครบทั้ง 81 ภาษา และทุกรูปแบบการส่งออก ไม่มีลายน้ำ ไม่มีวันหมดอายุช่วงทดลองใช้ ไม่ต้องสมัครสมาชิก",
    },
    showcases: [
      "ลากและวางสกรีนช็อตหลายภาพพร้อมกัน Screenshot Bro จะนำเข้าทั้งหมดและใส่กรอบอุปกรณ์ให้แต่ละภาพโดยอัตโนมัติ ไม่ต้องจัดวางเอง ไม่ต้องทำทีละภาพให้เสียเวลา",
      "เชื่อมต่อคีย์ API ของ App Store Connect เพียงครั้งเดียว แล้วส่งสกรีนช็อตที่เรนเดอร์แล้วไปยังแอป เวอร์ชัน ประเภทหน้าจอ และภาษาที่ถูกต้องได้โดยตรง ตรวจจับประเภทหน้าจออัตโนมัติ จับคู่ภาษา ตรวจสอบล่วงหน้า และแทนที่ได้ในรอบเดียว ไม่ต้องลากวางในเบราว์เซอร์",
      "เพิ่มสี่เหลี่ยม วงกลม ดาว ข้อความ รูปภาพ และ SVG จากนั้นปรับขนาด หมุน และจัดสไตล์ให้แต่ละชิ้น ตั้งค่าสีเติม การไล่ระดับสี ความทึบ เส้นขอบ และรัศมีมุมได้จาก inspector โดยตรง ซ้อนเลเยอร์ กด Shift ค้างขณะลากเพื่อล็อกอัตราส่วน และสแนปเพื่อจัดตำแหน่งได้แม่นยำระดับพิกเซล",
      "เลือกจากพรีเซ็ตการไล่ระดับสี 16 แบบ สร้างเองด้วยตัวแก้ไขแบบหลายจุดสี หรือใส่รูปภาพพร้อมโหมดเติมเต็ม พอดี ยืด และเรียงต่อกัน พื้นหลังสามารถขยายข้ามหลายเทมเพลตในแถวเดียวเพื่อการออกแบบที่ไร้รอยต่อจากขอบถึงขอบ ปรับมุม ความทึบ และจุดสี ทุกอย่างอัปเดตแบบเรียลไทม์",
      "เลือกจากคลังกรอบอุปกรณ์ ทั้ง iPhone, iPad, MacBook, iMac รวมถึงโทรศัพท์และแท็บเล็ต Android สลับกรอบ เลือกสีตัวเครื่อง และปรับให้เข้ากับแบรนด์ของคุณโดยไม่ต้องนำเข้าสกรีนช็อตใหม่",
      "เปิดเซิร์ฟเวอร์ MCP ในเครื่อง แล้ว Claude Code, Claude Desktop หรือ Cursor จะควบคุม Screenshot Bro ได้ ทั้งสร้างโปรเจกต์ จัดวางแถวและรูปทรง นำเข้าสกรีนช็อต แปลข้อความ ดูตัวอย่างที่เรนเดอร์แล้ว ส่งออก และซิงค์ชุดภาพไปยัง App Store Connect เซิร์ฟเวอร์รับฟังเฉพาะที่ 127.0.0.1 ต้องใช้โทเค็นจากการตั้งค่า และทุกการเปลี่ยนแปลงย้อนกลับได้ด้วย ⌘Z",
    ],
    workflow: [
      "เลือกขนาดอุปกรณ์ ทั้ง iPhone, iPad, Mac หรือโทรศัพท์และแท็บเล็ต Android ซึ่งแต่ละแบบตั้งค่าพิกเซลไว้ตามที่สโตร์นั้นกำหนด เพิ่มแถวได้มากเท่าที่ต้องการ",
      "ใส่กรอบอุปกรณ์ เพิ่มข้อความและรูปทรง เลือกพื้นหลัง เพิ่มภาษา แปลข้อความที่ขาดหายไปโดยอัตโนมัติ และปรับข้อความเฉพาะของแต่ละรูปทรง เพื่อให้ทุกภาษาสมบูรณ์แบบระดับพิกเซล",
      "กดส่งออก รับโฟลเดอร์ที่จัดตามภาษาและแถว พร้อมสกรีนช็อตทุกภาพในขนาดที่สโตร์กำหนดพอดี เพียงคลิกเดียว",
      "เชื่อมต่อคีย์ API เพียงครั้งเดียว แล้วส่งสกรีนช็อตไปยังแอป เวอร์ชัน ประเภทหน้าจอ และภาษาที่ถูกต้องได้โดยตรง ไม่ต้องลากวางเข้าเบราว์เซอร์เอง",
    ],
  },
  sv: {
    features: {
      templates: "Redigera en gång, uppdatera varje variant. Ändra en form eller text så slår ändringen igenom i alla dina skärmdumpar samtidigt.",
      project: "81 språkförval, från engelska till arabiska, hindi och CJK. Översätt saknad text automatiskt och finjustera sedan text, position och bilder per form, med koll på hur långt översättningen har kommit.",
      export: "Exportera PNG eller JPEG i exakt pixelstorlek för varje rad, för alla språk på en gång. Automatiskt ordnade mappar per språk och rad för App Store Connect, Google Play och lanseringsmaterial.",
      cloud: "Valfri synkronisering via iCloud Drive håller dina projekt tillgängliga på alla dina Mac-datorer, iPads och iPhones. Sammanslagning enligt principen senaste skrivning vinner, med konfliktlösning som tar hänsyn till borttagna objekt.",
      native: "Byggd med Swift och SwiftUI för Mac, iPad och iPhone. Ingen Electron, ingen webbläsarflik. Startar direkt, nativ prestanda, autosparning, fullständig ångra/gör om.",
      fonts: "Importera dina egna typsnittsfiler i .ttf, .otf eller .ttc. Använd valfritt typsnitt i textformer — utan systemtypsnittens begränsningar.",
      privacy: "Automatisk översättning körs på enheten via Apples Translation-ramverk. Inga API-nycklar, inga konton, ingen annonsspårning — projekt, typsnitt och skärmdumpar stannar på din enhet.",
      free: "1 projekt, 3 rader, 5 mallar per rad — med alla enhetsramar, alla 81 språk och alla exportformat. Ingen vattenstämpel, ingen provperiod som löper ut, ingen registrering.",
    },
    showcases: [
      "Dra och släpp flera skärmdumpar på en gång — Screenshot Bro importerar alla och lägger automatiskt in var och en i enhetsramen. Ingen manuell placering, inget mödosamt arbete en i taget.",
      "Anslut din App Store Connect-API-nyckel en gång och skicka sedan renderade skärmdumpar direkt till rätt app, version, skärmtyp och språk. Automatiskt identifierade skärmtyper, språkmatchning, förhandskontroller och ersättning i ett svep — inget dra-och-släpp i webbläsaren.",
      "Lägg till rektanglar, cirklar, stjärnor, text, bilder och SVG:er — och ändra sedan storlek, rotera och styla var och en. Ställ in fyllnadsfärger, gradienter, opacitet, konturer och hörnradie direkt i inspektören. Stapla lager, Skift-dra för att låsa bildförhållandet och fäst mot pixelperfekt justering.",
      "Välj bland 16 gradientförval, bygg din egen med redigeraren för flera färgstopp eller släpp in bilder med lägena fyll, anpassa, sträck och sida vid sida. Bakgrunder kan spänna över flera mallar i en rad för sömlös design från kant till kant. Justera vinkel, opacitet och färgstopp — allt uppdateras live.",
      "Välj från ett bibliotek med enhetsramar — iPhone, iPad, MacBook, iMac samt Android-telefoner och -surfplattor. Byt ramar, välj färg på höljet och matcha ditt varumärke utan att importera skärmdumparna på nytt.",
      "Slå på den lokala MCP-servern så kan Claude Code, Claude Desktop eller Cursor styra Screenshot Bro: skapa ett projekt, lägga upp rader och former, importera skärmdumpar, översätta text, titta på renderade förhandsvisningar, exportera och synka uppsättningen till App Store Connect. Den lyssnar bara på 127.0.0.1, kräver en token från Inställningar och varje ändring ångras med ⌘Z.",
    ],
    workflow: [
      "Välj dina enhetsstorlekar — iPhone, iPad, Mac eller Android-telefon och -surfplatta, var och en förinställd på de pixlar som respektive butik kräver. Lägg till så många rader du behöver.",
      "Lägg in enhetsramar, lägg till text och former, välj en bakgrund. Lägg till språk, översätt saknad text automatiskt och finjustera textåsidosättningar per form så att varje språk förblir pixelperfekt.",
      "Tryck på exportera. Få mappar ordnade per språk och rad, med varje skärmdump i exakt den storlek butiken kräver. Ett klick.",
      "Anslut din API-nyckel en gång och skicka sedan skärmdumpar direkt till rätt app, version, skärmtyp och språk — utan manuellt dra-och-släpp i webbläsaren.",
    ],
  },
  da: {
    features: {
      templates: "Redigér én gang, og alle varianter opdateres. Ændr en form eller en tekst, og ændringen slår igennem på alle dine skærmbilleder på samme tid.",
      project: "81 sprogforudindstillinger fra engelsk til arabisk, hindi og CJK. Oversæt manglende tekst automatisk, og finjustér derefter tekst, placering og billeder pr. form med overstyringer og sporing af oversættelsesfremskridt.",
      export: "Eksportér PNG eller JPEG i den nøjagtige pixelstørrelse for hver række og for alle sprog på én gang. Mapper organiseres automatisk efter sprog og række til App Store Connect, Google Play og lanceringsmateriale.",
      cloud: "Valgfri synkronisering via iCloud Drive holder projekterne tilgængelige på alle dine Mac-computere, iPads og iPhones. Last-writer-wins-fletning med konfliktløsning, der tager højde for slettede elementer (tombstones).",
      native: "Bygget med Swift og SwiftUI til Mac, iPad og iPhone. Ingen Electron, ingen browserfane. Øjeblikkelig opstart, nativ ydeevne, automatisk lagring og fuld fortryd/gentag.",
      fonts: "Importér dine egne skrifttypefiler i .ttf, .otf eller .ttc. Brug en hvilken som helst skrifttype i tekstformer — ingen begrænsning til systemets skrifttyper.",
      privacy: "Automatisk oversættelse kører på enheden via Apples Translation-framework. Ingen API-nøgler, ingen konti, ingen annoncesporing — projekter, skrifttyper og skærmbilleder bliver på din enhed.",
      free: "1 projekt, 3 rækker, 5 skabeloner pr. række — med alle enhedsrammer, alle 81 sprog og alle eksportformater. Intet vandmærke, ingen prøveperiode der udløber, ingen tilmelding.",
    },
    showcases: [
      "Træk og slip flere skærmbilleder på én gang — Screenshot Bro importerer dem alle og placerer automatisk hvert enkelt i enhedsrammen. Ingen manuel placering, ingen besværlig arbejdsgang ét billede ad gangen.",
      "Forbind din App Store Connect API-nøgle én gang, og send derefter de renderede skærmbilleder direkte til den rigtige app, version, skærmtype og det rigtige sprog. Automatisk registrerede skærmtyper, sprogmatchning, forhåndstjek og udskiftning i én omgang — ingen træk-og-slip i browseren.",
      "Tilføj rektangler, cirkler, stjerner, tekst, billeder og SVG'er — og skalér, rotér og style hver enkelt. Indstil fyldfarver, gradienter, gennemsigtighed, konturer og hjørneradius direkte fra inspektøren. Stak lag, Shift-træk for at låse billedformatet, og fastgør til pixelpræcis justering.",
      "Vælg mellem 16 forudindstillede gradienter, byg dine egne med editoren til flere farvestop, eller indsæt billeder med tilstandene udfyld, tilpas, stræk og fliselæg. Baggrunde kan strække sig over flere skabeloner i en række for sømløse design fra kant til kant. Justér vinkel, gennemsigtighed og farvestop — alt opdateres live.",
      "Vælg fra et bibliotek af enhedsrammer — iPhone, iPad, MacBook, iMac samt Android-telefoner og -tablets. Skift rammer, vælg kabinetfarver, og match dit brand uden at importere skærmbillederne igen.",
      "Slå den lokale MCP-server til, så kan Claude Code, Claude Desktop eller Cursor styre Screenshot Bro: oprette et projekt, opsætte rækker og former, importere skærmbilleder, oversætte tekst, se på renderede forhåndsvisninger, eksportere og synkronisere sættet til App Store Connect. Serveren lytter kun på 127.0.0.1, kræver et token fra Indstillinger, og alle ændringer kan fortrydes med ⌘Z.",
    ],
    workflow: [
      "Vælg dine enhedsstørrelser — iPhone, iPad, Mac eller Android-telefon og -tablet, hver forudindstillet til de pixelmål, butikken forventer. Tilføj så mange rækker, du har brug for.",
      "Indsæt enhedsrammer, tilføj tekst og former, og vælg en baggrund. Tilføj sprog, oversæt manglende tekst automatisk, og finjustér tekstoverstyringer pr. form, så alle sprog forbliver pixelperfekte.",
      "Tryk på eksportér. Du får mapper organiseret efter sprog og række, med hvert skærmbillede i præcis den størrelse, butikken forventer. Ét klik.",
      "Forbind din API-nøgle én gang, og send derefter skærmbilleder direkte til den rigtige app, version, skærmtype og det rigtige sprog — uden manuel træk-og-slip i browseren.",
    ],
  },
  fi: {
    features: {
      templates: "Muokkaa kerran, päivitä kaikki versiot. Muuta muotoa tai tekstiä, niin muutos näkyy kaikissa kuvakaappauksissasi samanaikaisesti.",
      project: "81 kieliesiasetusta englannista arabiaan, hindiin ja CJK-kieliin. Käännä puuttuvat tekstit automaattisesti ja hienosäädä sitten muotokohtaisia tekstin, sijainnin ja kuvien ohituksia käännösten edistymisen seurannan avulla.",
      export: "Vie PNG- tai JPEG-kuvat kunkin rivin tarkassa pikselikoossa kaikille kielille kerralla. Kansiot järjestyvät automaattisesti kielen ja rivin mukaan App Store Connectia, Google Playta ja julkaisumateriaaleja varten.",
      cloud: "Valinnainen iCloud Drive -synkronointi pitää projektit saatavilla kaikilla Maceillasi, iPadeillasi ja iPhoneillasi. Last-writer-wins-yhdistäminen ja poistomerkinnät (tombstones) huomioiva ristiriitojen ratkaisu.",
      native: "Rakennettu Swiftillä ja SwiftUI:lla Macille, iPadille ja iPhonelle. Ei Electronia, ei selainvälilehteä. Välitön käynnistys, natiivi suorituskyky, automaattinen tallennus sekä täysi kumoa/tee uudelleen.",
      fonts: "Tuo omat .ttf-, .otf- tai .ttc-fonttitiedostosi. Käytä mitä tahansa kirjasinta tekstimuodoissa — ei järjestelmäfonttien rajoituksia.",
      privacy: "Automaattinen käännös toimii laitteella Applen Translation-kehyksen kautta. Ei API-avaimia, ei tilejä, ei mainosseurantaa — projektit, fontit ja kuvakaappaukset pysyvät laitteellasi.",
      free: "1 projekti, 3 riviä, 5 mallia riviä kohden — mukana kaikki laitekehykset, kaikki 81 kieltä ja kaikki vientimuodot. Ei vesileimaa, ei vanhenevaa kokeilujaksoa, ei rekisteröitymistä.",
    },
    showcases: [
      "Vedä ja pudota useita kuvakaappauksia kerralla — Screenshot Bro tuo ne kaikki ja sijoittaa jokaisen automaattisesti laitekehykseen. Ei käsin asettelua eikä työlästä yksi kerrallaan -työnkulkua.",
      "Yhdistä App Store Connect -API-avaimesi kerran ja lähetä sitten renderöidyt kuvakaappaukset suoraan oikeaan sovellukseen, versioon, näyttötyyppiin ja kieleen. Automaattisesti tunnistetut näyttötyypit, kielten täsmäytys, ennakkotarkistukset ja korvaus yhdellä kertaa — ei vetämistä ja pudottamista selaimessa.",
      "Lisää suorakulmioita, ympyröitä, tähtiä, tekstiä, kuvia ja SVG-tiedostoja — ja muuta jokaisen kokoa, kierrä ja muotoile niitä. Aseta täyttövärit, liukuvärit, peittävyys, ääriviivat ja kulmien pyöristys suoraan tarkastimesta. Pinoa tasoja, lukitse kuvasuhde Shift-vedolla ja kohdista pikselintarkasti.",
      "Valitse 16 valmiista liukuväristä, rakenna omasi monipisteeditorilla tai lisää kuvia täyttö-, sovitus-, venytys- ja ruudutustiloilla. Taustat voivat ulottua rivin useiden mallien yli saumattomiksi, reunasta reunaan ulottuviksi kokonaisuuksiksi. Säädä kulmaa, peittävyyttä ja väripisteitä — kaikki päivittyy reaaliajassa.",
      "Valitse laitekehysten kirjastosta — iPhone, iPad, MacBook, iMac sekä Android-puhelimet ja -tabletit. Vaihda kehyksiä, valitse rungon värit ja sovita ne brändiisi tuomatta kuvakaappauksia uudelleen.",
      "Ota paikallinen MCP-palvelin käyttöön, niin Claude Code, Claude Desktop tai Cursor voi ohjata Screenshot Bro -sovellusta: luoda projektin, asetella rivit ja muodot, tuoda kuvakaappauksia, kääntää tekstejä, katsoa renderöityjä esikatseluja, viedä ja synkronoida sarjan App Store Connectiin. Palvelin kuuntelee vain osoitteessa 127.0.0.1, vaatii tunnisteen Asetuksista, ja jokaisen muutoksen voi kumota ⌘Z:lla.",
    ],
    workflow: [
      "Valitse laitekoot — iPhone, iPad, Mac tai Android-puhelin ja -tabletti, jokainen valmiiksi asetettu kaupan edellyttämiin pikselimittoihin. Lisää niin monta riviä kuin tarvitset.",
      "Lisää laitekehykset, tekstit ja muodot ja valitse tausta. Lisää kieliä, käännä puuttuvat tekstit automaattisesti ja hienosäädä muotokohtaisia tekstin ohituksia, jotta jokainen kieli pysyy pikselintarkkana.",
      "Paina Vie. Saat kansiot järjestettyinä kielen ja rivin mukaan, ja jokainen kuvakaappaus on täsmälleen kaupan edellyttämän kokoinen. Yksi napsautus.",
      "Yhdistä API-avaimesi kerran ja lähetä sitten kuvakaappaukset suoraan oikeaan sovellukseen, versioon, näyttötyyppiin ja kieleen — ei käsin vetämistä ja pudottamista selaimeen.",
    ],
  },
  no: {
    features: {
      templates: "Rediger én gang, oppdater alle varianter. Endre en form eller en tekst, og endringen slår gjennom på alle skjermbildene dine samtidig.",
      project: "81 språkforhåndsinnstillinger fra engelsk til arabisk, hindi og CJK. Oversett manglende tekst automatisk, og finjuster deretter tekst, plassering og bilder per form med overstyringer og sporing av oversettelsesfremdrift.",
      export: "Eksporter PNG eller JPEG i nøyaktig pikselstørrelse for hver rad, for alle språk samtidig. Mapper organiseres automatisk etter språk og rad for App Store Connect, Google Play og lanseringsmateriell.",
      cloud: "Valgfri synkronisering via iCloud Drive holder prosjektene tilgjengelige på alle dine Mac-er, iPader og iPhoner. Last-writer-wins-sammenslåing med konfliktløsning som tar hensyn til slettede elementer (tombstones).",
      native: "Bygget med Swift og SwiftUI for Mac, iPad og iPhone. Ingen Electron, ingen nettleserfane. Umiddelbar oppstart, nativ ytelse, automatisk lagring og full angre/gjør om.",
      fonts: "Importer dine egne fontfiler i .ttf, .otf eller .ttc. Bruk hvilken som helst skrifttype i tekstformer — ingen begrensning til systemfonter.",
      privacy: "Automatisk oversettelse kjører på enheten via Apples Translation-rammeverk. Ingen API-nøkler, ingen kontoer, ingen annonsesporing — prosjekter, fonter og skjermbilder blir værende på enheten din.",
      free: "1 prosjekt, 3 rader, 5 maler per rad — med alle enhetsrammer, alle 81 språk og alle eksportformater. Ingen vannmerke, ingen prøveperiode som utløper, ingen registrering.",
    },
    showcases: [
      "Dra og slipp flere skjermbilder samtidig — Screenshot Bro importerer alle og plasserer automatisk hvert enkelt i enhetsrammen. Ingen manuell plassering, ingen tungvint arbeidsflyt ett bilde om gangen.",
      "Koble til App Store Connect API-nøkkelen din én gang, og send deretter de rendrede skjermbildene rett til riktig app, versjon, skjermtype og språk. Automatisk gjenkjente skjermtyper, språkmatching, forhåndskontroller og utskifting i én omgang — ingen dra-og-slipp i nettleseren.",
      "Legg til rektangler, sirkler, stjerner, tekst, bilder og SVG-er — og endre størrelse, roter og style hver enkelt. Angi fyllfarger, gradienter, gjennomsiktighet, konturer og hjørneradius rett fra inspektøren. Stable lag, Shift-dra for å låse sideforholdet, og fest elementer med pikselperfekt justering.",
      "Velg blant 16 forhåndsinnstilte gradienter, lag dine egne med editoren for flere fargestopp, eller sett inn bilder med modusene fyll, tilpass, strekk og flislegg. Bakgrunner kan strekke seg over flere maler i en rad for sømløse design fra kant til kant. Juster vinkel, gjennomsiktighet og fargestopp — alt oppdateres live.",
      "Velg fra et bibliotek med enhetsrammer — iPhone, iPad, MacBook, iMac og Android-telefoner og -nettbrett. Bytt rammer, velg kabinettfarger og tilpass dem merkevaren din uten å importere skjermbildene på nytt.",
      "Slå på den lokale MCP-serveren, så kan Claude Code, Claude Desktop eller Cursor styre Screenshot Bro: opprette et prosjekt, sette opp rader og former, importere skjermbilder, oversette tekst, se på rendrede forhåndsvisninger, eksportere og synkronisere settet til App Store Connect. Serveren lytter bare på 127.0.0.1, krever et token fra Innstillinger, og alle endringer kan angres med ⌘Z.",
    ],
    workflow: [
      "Velg enhetsstørrelsene dine — iPhone, iPad, Mac eller Android-telefon og -nettbrett, hver forhåndsinnstilt til pikslene butikken forventer. Legg til så mange rader du trenger.",
      "Sett inn enhetsrammer, legg til tekst og former, og velg en bakgrunn. Legg til språk, oversett manglende tekst automatisk, og finjuster tekstoverstyringer per form så hvert språk forblir pikselperfekt.",
      "Trykk på eksporter. Du får mapper organisert etter språk og rad, med hvert skjermbilde i nøyaktig den størrelsen butikken forventer. Ett klikk.",
      "Koble til API-nøkkelen din én gang, og send deretter skjermbilder rett til riktig app, versjon, skjermtype og språk — uten manuell dra-og-slipp i nettleseren.",
    ],
  },
  cs: {
    features: {
      templates: "Upravte jednou, aktualizujte všechny varianty. Změňte tvar nebo text a změna se promítne do všech vašich snímků najednou.",
      project: "81 jazykových předvoleb od angličtiny po arabštinu, hindštinu a jazyky CJK. Nechte automaticky přeložit chybějící texty a pak dolaďte text, umístění a obrázky jednotlivých tvarů pomocí přepisů se sledováním postupu překladu.",
      export: "Exportujte PNG nebo JPEG v přesné pixelové velikosti každého řádku, pro všechny jazyky najednou. Složky se automaticky třídí podle jazyka a řádku pro App Store Connect, Google Play i materiály k vydání.",
      cloud: "Volitelná synchronizace přes iCloud Drive udržuje projekty dostupné na všech vašich Macích, iPadech a iPhonech. Slučování podle principu last-writer-wins s řešením konfliktů, které zohledňuje smazané položky (tombstones).",
      native: "Postaveno ve Swiftu a SwiftUI pro Mac, iPad a iPhone. Žádný Electron, žádná záložka prohlížeče. Okamžité spuštění, nativní výkon, automatické ukládání a plné zpět/znovu.",
      fonts: "Importujte vlastní soubory písem .ttf, .otf nebo .ttc. V textových tvarech použijte jakékoli písmo — bez omezení na systémová písma.",
      privacy: "Automatický překlad běží přímo v zařízení přes framework Translation od Applu. Žádné API klíče, žádné účty, žádné reklamní sledování — projekty, písma i snímky zůstávají ve vašem zařízení.",
      free: "1 projekt, 3 řádky, 5 šablon na řádek — se všemi rámečky zařízení, všemi 81 jazyky a všemi formáty exportu. Bez vodoznaku, bez vypršení zkušební doby, bez registrace.",
    },
    showcases: [
      "Přetáhněte několik snímků obrazovky najednou — Screenshot Bro je všechny naimportuje a každý automaticky vloží do rámečku zařízení. Žádné ruční umisťování, žádná zdlouhavá práce s jedním snímkem po druhém.",
      "Jednou připojte svůj API klíč k App Store Connect a pak posílejte vyrenderované snímky přímo do správné aplikace, verze, typu displeje a jazyka. Automaticky rozpoznané typy displejů, párování jazyků, předběžné kontroly a nahrazení v jediném průchodu — žádné přetahování v prohlížeči.",
      "Přidávejte obdélníky, kruhy, hvězdy, text, obrázky a SVG — a každý prvek zvětšujte, otáčejte a stylujte. Nastavte barvy výplně, přechody, průhlednost, obrysy a zaoblení rohů přímo v inspektoru. Skládejte vrstvy, tažením se Shiftem zamkněte poměr stran a zarovnávejte s pixelovou přesností.",
      "Vyberte si z 16 předvoleb přechodů, vytvořte vlastní v editoru s více barevnými body nebo vložte obrázky v režimech vyplnit, přizpůsobit, roztáhnout a dlaždice. Pozadí se může táhnout přes více šablon v řádku pro plynulé návrhy od okraje k okraji. Upravujte úhel, průhlednost a barevné body — vše se aktualizuje živě.",
      "Vyberte si z knihovny rámečků zařízení — iPhone, iPad, MacBook, iMac a telefony a tablety s Androidem. Měňte rámečky, volte barvy těla a slaďte je se svou značkou bez nového importu snímků.",
      "Zapněte lokální MCP server a Claude Code, Claude Desktop nebo Cursor může ovládat Screenshot Bro: vytvořit projekt, rozvrhnout řádky a tvary, naimportovat snímky, přeložit texty, prohlédnout si vyrenderované náhledy, exportovat a synchronizovat sadu do App Store Connect. Server naslouchá pouze na 127.0.0.1, vyžaduje token z Nastavení a každou změnu lze vrátit pomocí ⌘Z.",
    ],
    workflow: [
      "Vyberte velikosti zařízení — iPhone, iPad, Mac nebo telefon a tablet s Androidem, každá předem nastavená na pixely, které obchod očekává. Přidejte tolik řádků, kolik potřebujete.",
      "Vložte rámečky zařízení, přidejte text a tvary a vyberte pozadí. Přidejte jazyky, nechte automaticky přeložit chybějící texty a dolaďte textové přepisy jednotlivých tvarů, aby každý jazyk zůstal pixelově přesný.",
      "Klikněte na export. Dostanete složky uspořádané podle jazyka a řádku a každý snímek přesně ve velikosti, kterou obchod očekává. Jedním kliknutím.",
      "Jednou připojte svůj API klíč a pak posílejte snímky přímo do správné aplikace, verze, typu displeje a jazyka — bez ručního přetahování do prohlížeče.",
    ],
  },
  ro: {
    features: {
      templates: "Editezi o dată, se actualizează toate variantele. Modifică o formă sau un text, iar schimbarea se aplică simultan pe toate capturile tale de ecran.",
      project: "81 de presetări de limbă, de la engleză la arabă, hindi și CJK. Tradu automat textele lipsă, apoi ajustează fin textul, poziția și imaginile fiecărei forme prin suprascrieri, cu urmărirea progresului traducerii.",
      export: "Exportă PNG sau JPEG la dimensiunea exactă în pixeli a fiecărui rând, pentru toate limbile deodată. Folderele sunt organizate automat pe limbă și rând pentru App Store Connect, Google Play și materialele de lansare.",
      cloud: "Sincronizarea opțională prin iCloud Drive îți păstrează proiectele disponibile pe toate dispozitivele tale Mac, iPad și iPhone. Îmbinare de tip last-writer-wins, cu rezolvarea conflictelor care ține cont de elementele șterse (tombstones).",
      native: "Construită cu Swift și SwiftUI pentru Mac, iPad și iPhone. Fără Electron, fără filă de browser. Pornire instantanee, performanță nativă, salvare automată și anulare/refacere completă.",
      fonts: "Importă propriile fișiere de font .ttf, .otf sau .ttc. Folosește orice font în formele de text — fără limitările fonturilor de sistem.",
      privacy: "Traducerea automată rulează pe dispozitiv prin framework-ul Translation de la Apple. Fără chei API, fără conturi, fără urmărire publicitară — proiectele, fonturile și capturile de ecran rămân pe dispozitivul tău.",
      free: "1 proiect, 3 rânduri, 5 șabloane pe rând — cu toate ramele de dispozitive, toate cele 81 de limbi și toate formatele de export. Fără filigran, fără perioadă de probă care expiră, fără înregistrare.",
    },
    showcases: [
      "Trage și plasează mai multe capturi de ecran deodată — Screenshot Bro le importă pe toate și încadrează automat fiecare captură în rama dispozitivului. Fără poziționare manuală, fără munca obositoare de a le lua pe rând.",
      "Conectează o singură dată cheia API App Store Connect, apoi trimite capturile randate direct în aplicația, versiunea, tipul de afișaj și limba potrivite. Tipuri de afișaj detectate automat, potrivirea limbilor, verificări preliminare și înlocuire dintr-o singură trecere — fără drag-and-drop în browser.",
      "Adaugă dreptunghiuri, cercuri, stele, text, imagini și SVG-uri — apoi redimensionează, rotește și stilizează fiecare element. Setează culori de umplere, degradeuri, opacitate, contururi și raza colțurilor direct din inspector. Suprapune straturi, trage cu Shift pentru a bloca raportul de aspect și aliniază totul la nivel de pixel.",
      "Alege dintre 16 presetări de degradeuri, creează-ți propriile degradeuri cu editorul cu mai multe puncte de culoare sau adaugă imagini cu modurile umplere, încadrare, întindere și mozaic. Fundalurile se pot extinde peste mai multe șabloane dintr-un rând, pentru designuri continue, de la margine la margine. Ajustează unghiul, opacitatea și punctele de culoare — totul se actualizează în timp real.",
      "Alege dintr-o bibliotecă de rame de dispozitive — iPhone, iPad, MacBook, iMac și telefoane și tablete Android. Schimbă ramele, alege culorile carcasei și potrivește-le cu brandul tău fără să reimporți capturile.",
      "Activează serverul MCP local, iar Claude Code, Claude Desktop sau Cursor poate controla Screenshot Bro: creează un proiect, aranjează rânduri și forme, importă capturi, traduce textele, se uită la previzualizările randate, exportă și sincronizează setul în App Store Connect. Serverul ascultă doar pe 127.0.0.1, are nevoie de un token din Setări, iar orice modificare se anulează cu ⌘Z.",
    ],
    workflow: [
      "Alege dimensiunile dispozitivelor — iPhone, iPad, Mac sau telefon și tabletă Android, fiecare presetat la pixelii pe care îi așteaptă magazinul. Adaugă câte rânduri ai nevoie.",
      "Adaugă rame de dispozitive, text și forme și alege un fundal. Adaugă limbi, tradu automat textele lipsă și ajustează suprascrierile de text pentru fiecare formă, ca fiecare limbă să rămână perfectă la nivel de pixel.",
      "Apasă pe export. Primești foldere organizate pe limbă și rând, cu fiecare captură exact la dimensiunea cerută de magazin. Un singur clic.",
      "Conectează-ți o singură dată cheia API, apoi trimite capturile direct în aplicația, versiunea, tipul de afișaj și limba potrivite — fără drag-and-drop manual în browser.",
    ],
  },
  ms: {
    features: {
      templates: "Sunting sekali, kemas kini setiap variasi. Ubah bentuk atau teks dan perubahan itu diterapkan pada semua tangkapan skrin anda serentak.",
      project: "81 pratetap bahasa daripada bahasa Inggeris hingga bahasa Arab, Hindi dan CJK. Terjemah teks yang tiada secara automatik, kemudian perhalusi teks, kedudukan dan imej setiap bentuk dengan gantian, berserta penjejakan kemajuan terjemahan.",
      export: "Eksport PNG atau JPEG pada saiz piksel tepat setiap baris, untuk semua bahasa sekali gus. Folder disusun secara automatik mengikut bahasa dan baris untuk App Store Connect, Google Play dan aset pelancaran.",
      cloud: "Penyelarasan iCloud Drive pilihan memastikan projek tersedia pada semua Mac, iPad dan iPhone anda. Gabungan last-writer-wins dengan penyelesaian konflik yang mengambil kira item yang dipadam (tombstones).",
      native: "Dibina dengan Swift dan SwiftUI untuk Mac, iPad dan iPhone. Tiada Electron, tiada tab pelayar. Pelancaran serta-merta, prestasi natif, simpan automatik dan buat asal/buat semula sepenuhnya.",
      fonts: "Import fail fon .ttf, .otf atau .ttc anda sendiri. Gunakan apa-apa muka taip dalam bentuk teks — tiada had fon sistem.",
      privacy: "Terjemahan automatik berjalan pada peranti melalui rangka kerja Translation Apple. Tiada kunci API, tiada akaun, tiada penjejakan iklan — projek, fon dan tangkapan skrin kekal pada peranti anda.",
      free: "1 projek, 3 baris, 5 templat setiap baris — dengan semua bingkai peranti, kesemua 81 bahasa dan semua format eksport. Tiada tera air, tiada tempoh percubaan yang tamat, tiada pendaftaran.",
    },
    showcases: [
      "Tarik dan lepas beberapa tangkapan skrin sekali gus — Screenshot Bro mengimport kesemuanya dan meletakkan setiap satu ke dalam bingkai peranti secara automatik. Tiada peletakan manual, tiada kerja leceh satu demi satu.",
      "Sambungkan kunci API App Store Connect anda sekali, kemudian hantar tangkapan skrin yang telah dirender terus ke aplikasi, versi, jenis paparan dan bahasa yang betul. Jenis paparan dikesan secara automatik, padanan bahasa, semakan awal dan penggantian dalam satu laluan — tiada tarik dan lepas dalam pelayar.",
      "Tambah segi empat, bulatan, bintang, teks, imej dan SVG — kemudian ubah saiz, putar dan gayakan setiap satu. Tetapkan warna isian, kecerunan, kelegapan, garis luar dan jejari sudut terus daripada pemeriksa. Susun lapisan, tarik dengan Shift untuk mengunci nisbah aspek dan jajarkan dengan ketepatan piksel.",
      "Pilih daripada 16 pratetap kecerunan, bina sendiri dengan editor berbilang titik warna, atau masukkan imej dengan mod isi, muat, regang dan jubin. Latar belakang boleh merentasi beberapa templat dalam satu baris untuk reka bentuk lancar dari tepi ke tepi. Laraskan sudut, kelegapan dan titik warna — semuanya dikemas kini secara langsung.",
      "Pilih daripada pustaka bingkai peranti — iPhone, iPad, MacBook, iMac serta telefon dan tablet Android. Tukar bingkai, pilih warna badan dan padankan dengan jenama anda tanpa mengimport semula tangkapan skrin.",
      "Hidupkan pelayan MCP setempat dan Claude Code, Claude Desktop atau Cursor boleh mengendalikan Screenshot Bro: mencipta projek, menyusun baris dan bentuk, mengimport tangkapan skrin, menterjemah teks, melihat pratonton yang dirender, mengeksport dan menyelaraskan set itu ke App Store Connect. Pelayan hanya mendengar pada 127.0.0.1, memerlukan token daripada Tetapan, dan setiap perubahan boleh dibuat asal dengan ⌘Z.",
    ],
    workflow: [
      "Pilih saiz peranti anda — iPhone, iPad, Mac atau telefon dan tablet Android, setiap satu dipratetap kepada piksel yang dikehendaki oleh gedungnya. Tambah seberapa banyak baris yang anda perlukan.",
      "Masukkan bingkai peranti, tambah teks dan bentuk, pilih latar belakang. Tambah bahasa, terjemah teks yang tiada secara automatik dan perhalusi gantian teks setiap bentuk supaya setiap bahasa kekal tepat hingga ke piksel.",
      "Tekan eksport. Dapatkan folder yang tersusun mengikut bahasa dan baris, setiap tangkapan skrin pada saiz tepat yang dikehendaki gedung. Satu klik.",
      "Sambungkan kunci API anda sekali, kemudian hantar tangkapan skrin terus ke aplikasi, versi, jenis paparan dan bahasa yang betul — tiada tarik dan lepas manual ke dalam pelayar.",
    ],
  },
};
