import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("privacy", "routes/privacy.tsx"),
  route("terms", "routes/terms.tsx"),
  route("changelog", "routes/changelog.tsx"),
  route("support", "routes/support.tsx"),
  route("blog", "routes/blog._index.tsx"),
  route(":locale/blog", "routes/blog._index.tsx", { id: "blog-locale" }),
  route("blog/app-store-screenshot-examples", "routes/blog.app-store-screenshot-examples.tsx"),
  route("blog/google-play-feature-graphic-size-template-examples", "routes/blog.google-play-feature-graphic-size-template-examples.tsx"),
  route("blog/app-store-screenshots-rejected-fix", "routes/blog.app-store-screenshots-rejected-fix.tsx"),
  route("blog/google-play-screenshot-rejected-fix", "routes/blog.google-play-screenshot-rejected-fix.tsx"),
  route("blog/app-store-screenshot-order", "routes/blog.app-store-screenshot-order.tsx"),
  route("blog/app-store-screenshot-copywriting-examples", "routes/blog.app-store-screenshot-copywriting-examples.tsx"),
  route("blog/app-store-screenshot-mistakes", "routes/blog.app-store-screenshot-mistakes.tsx"),
  route("blog/iphone-ipad-app-store-screenshots", "routes/blog.iphone-ipad-app-store-screenshots.tsx"),
  route("blog/google-play-store-listing-graphics-checklist", "routes/blog.google-play-store-listing-graphics-checklist.tsx"),
  route("blog/seasonal-app-store-screenshots", "routes/blog.seasonal-app-store-screenshots.tsx"),
  route("blog/app-store-screenshot-localization-guide", "routes/blog.app-store-screenshot-localization-guide.tsx"),
  route("blog/popular-figma-templates-app-store-screenshots-device-mockups", "routes/blog.popular-figma-templates-app-store-screenshots-device-mockups.tsx"),
  route("blog/app-store-screenshot-designers-creators-to-follow", "routes/blog.app-store-screenshot-designers-creators-to-follow.tsx"),
  route("blog/google-play-screenshot-sizes-requirements", "routes/blog.google-play-screenshot-sizes-requirements.tsx"),
  route(":locale/blog/google-play-screenshot-sizes-requirements", "routes/blog.google-play-screenshot-sizes-requirements.tsx", { id: "blog-google-play-screenshot-sizes-requirements-locale" }),
  route("blog/ab-test-app-store-screenshots", "routes/blog.ab-test-app-store-screenshots.tsx"),
  route(":locale/blog/ab-test-app-store-screenshots", "routes/blog.ab-test-app-store-screenshots.tsx", { id: "blog-ab-test-app-store-screenshots-locale" }),
  route("blog/custom-product-pages-app-store-screenshots", "routes/blog.custom-product-pages-app-store-screenshots.tsx"),
  route(":locale/blog/custom-product-pages-app-store-screenshots", "routes/blog.custom-product-pages-app-store-screenshots.tsx", { id: "blog-custom-product-pages-app-store-screenshots-locale" }),
  route("blog/design-app-store-screenshots-in-figma", "routes/blog.design-app-store-screenshots-in-figma.tsx"),
  route(":locale/blog/design-app-store-screenshots-in-figma", "routes/blog.design-app-store-screenshots-in-figma.tsx", { id: "blog-design-app-store-screenshots-in-figma-locale" }),
  route("blog/best-app-store-screenshot-tools", "routes/blog.best-app-store-screenshot-tools.tsx"),
  route(":locale/blog/best-app-store-screenshot-tools", "routes/blog.best-app-store-screenshot-tools.tsx", { id: "blog-best-app-store-screenshot-tools-locale" }),
  route("blog/make-and-ship-screenshots-with-fastlane", "routes/blog.make-and-ship-screenshots-with-fastlane.tsx"),
  route(":locale/blog/make-and-ship-screenshots-with-fastlane", "routes/blog.make-and-ship-screenshots-with-fastlane.tsx", { id: "blog-make-and-ship-screenshots-with-fastlane-locale" }),
  route("blog/upload-screenshots-to-app-store-connect", "routes/blog.upload-screenshots-to-app-store-connect.tsx"),
  route(":locale/blog/upload-screenshots-to-app-store-connect", "routes/blog.upload-screenshots-to-app-store-connect.tsx", { id: "blog-upload-screenshots-to-app-store-connect-locale" }),
  route("blog/screenshot-sizes-app-store-google-play", "routes/blog.screenshot-sizes-app-store-google-play.tsx"),
  route(":locale/blog/screenshot-sizes-app-store-google-play", "routes/blog.screenshot-sizes-app-store-google-play.tsx", { id: "blog-screenshot-sizes-app-store-google-play-locale" }),
  route("blog/app-store-screenshot-sizes", "routes/blog.app-store-screenshot-sizes.tsx"),
  route(":locale/blog/app-store-screenshot-sizes", "routes/blog.app-store-screenshot-sizes.tsx", { id: "blog-app-store-screenshot-sizes-locale" }),
  route("blog/screenshots-that-convert", "routes/blog.screenshots-that-convert.tsx"),
  route(":locale/blog/screenshots-that-convert", "routes/blog.screenshots-that-convert.tsx", { id: "blog-screenshots-that-convert-locale" }),
  route("blog/localize-app-store-screenshots", "routes/blog.localize-app-store-screenshots.tsx"),
  route(":locale/blog/localize-app-store-screenshots", "routes/blog.localize-app-store-screenshots.tsx", { id: "blog-localize-app-store-screenshots-locale" }),
  route("docs", "routes/docs._index.tsx"),
  route(":locale/docs", "routes/docs._index.tsx", { id: "docs-index-locale" }),
  route("docs/help", "routes/docs.help.tsx"),
  route(":locale/docs/help", "routes/docs.help.tsx", { id: "docs-help-locale" }),
  route("docs/project-schema", "routes/docs.project-schema.tsx"),
  route(":locale/docs/project-schema", "routes/docs.project-schema.tsx", { id: "docs-project-schema-locale" }),
  route("vs/fastlane-snapshot", "routes/vs.fastlane-snapshot.tsx"),
  route("sitemap.xml", "routes/sitemap[.]xml.tsx"),
  route(":locale", "routes/localized-home.tsx"),
  route("*", "routes/$.tsx"),
] satisfies RouteConfig;
