import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("privacy", "routes/privacy.tsx"),
  route(":locale/privacy", "routes/privacy.tsx", { id: "privacy-locale" }),
  route("terms", "routes/terms.tsx"),
  route(":locale/terms", "routes/terms.tsx", { id: "terms-locale" }),
  route("changelog", "routes/changelog.tsx"),
  route(":locale/changelog", "routes/changelog.tsx", { id: "changelog-locale" }),
  route("support", "routes/support.tsx"),
  route(":locale/support", "routes/support.tsx", { id: "support-locale" }),
  route("tutorials", "routes/tutorials.tsx"),
  route(":locale/tutorials", "routes/tutorials.tsx", { id: "tutorials-locale" }),
  route(
    "tutorials/how-to-use-screenshot-bro",
    "routes/tutorials.how-to-use-screenshot-bro.tsx",
  ),
  route(
    ":locale/tutorials/how-to-use-screenshot-bro",
    "routes/tutorials.how-to-use-screenshot-bro.tsx",
    { id: "tutorials-how-to-use-screenshot-bro-locale" },
  ),
  route("blog", "routes/blog._index.tsx"),
  route(":locale/blog", "routes/blog._index.tsx", { id: "blog-locale" }),
  route("blog/screenshot-bro-mcp-server", "routes/blog.screenshot-bro-mcp-server.tsx"),
  route(":locale/blog/screenshot-bro-mcp-server", "routes/blog.screenshot-bro-mcp-server.tsx", { id: "blog-screenshot-bro-mcp-server-locale" }),
  route("blog/best-app-store-screenshot-tools-for-mac", "routes/blog.best-app-store-screenshot-tools-for-mac.tsx"),
  route(":locale/blog/best-app-store-screenshot-tools-for-mac", "routes/blog.best-app-store-screenshot-tools-for-mac.tsx", { id: "blog-best-app-store-screenshot-tools-for-mac-locale" }),
  route("blog/best-app-screenshot-localization-tools", "routes/blog.best-app-screenshot-localization-tools.tsx"),
  route(":locale/blog/best-app-screenshot-localization-tools", "routes/blog.best-app-screenshot-localization-tools.tsx", { id: "blog-best-app-screenshot-localization-tools-locale" }),
  route("blog/best-google-play-screenshot-tools", "routes/blog.best-google-play-screenshot-tools.tsx"),
  route(":locale/blog/best-google-play-screenshot-tools", "routes/blog.best-google-play-screenshot-tools.tsx", { id: "blog-best-google-play-screenshot-tools-locale" }),
  route("blog/screenshot-bro-alternatives", "routes/blog.screenshot-bro-alternatives.tsx"),
  route(":locale/blog/screenshot-bro-alternatives", "routes/blog.screenshot-bro-alternatives.tsx", { id: "blog-screenshot-bro-alternatives-locale" }),
  route("blog/appscreens-alternative", "routes/blog.appscreens-alternative.tsx"),
  route(":locale/blog/appscreens-alternative", "routes/blog.appscreens-alternative.tsx", { id: "blog-appscreens-alternative-locale" }),
  route("blog/screenshots-pro-alternative", "routes/blog.screenshots-pro-alternative.tsx"),
  route(":locale/blog/screenshots-pro-alternative", "routes/blog.screenshots-pro-alternative.tsx", { id: "blog-screenshots-pro-alternative-locale" }),
  route("blog/rotato-alternative", "routes/blog.rotato-alternative.tsx"),
  route(":locale/blog/rotato-alternative", "routes/blog.rotato-alternative.tsx", { id: "blog-rotato-alternative-locale" }),
  route("blog/placeit-alternative", "routes/blog.placeit-alternative.tsx"),
  route(":locale/blog/placeit-alternative", "routes/blog.placeit-alternative.tsx", { id: "blog-placeit-alternative-locale" }),
  route("blog/mockuuups-studio-alternative", "routes/blog.mockuuups-studio-alternative.tsx"),
  route(":locale/blog/mockuuups-studio-alternative", "routes/blog.mockuuups-studio-alternative.tsx", { id: "blog-mockuuups-studio-alternative-locale" }),
  route("blog/canva-app-store-screenshots", "routes/blog.canva-app-store-screenshots.tsx"),
  route(":locale/blog/canva-app-store-screenshots", "routes/blog.canva-app-store-screenshots.tsx", { id: "blog-canva-app-store-screenshots-locale" }),
  route("blog/appmockup-alternative", "routes/blog.appmockup-alternative.tsx"),
  route(":locale/blog/appmockup-alternative", "routes/blog.appmockup-alternative.tsx", { id: "blog-appmockup-alternative-locale" }),
  route("blog/screenshot-studio-alternative", "routes/blog.screenshot-studio-alternative.tsx"),
  route(":locale/blog/screenshot-studio-alternative", "routes/blog.screenshot-studio-alternative.tsx", { id: "blog-screenshot-studio-alternative-locale" }),
  route("blog/applaunchpad-alternative", "routes/blog.applaunchpad-alternative.tsx"),
  route(":locale/blog/applaunchpad-alternative", "routes/blog.applaunchpad-alternative.tsx", { id: "blog-applaunchpad-alternative-locale" }),
  route("blog/previewed-alternative", "routes/blog.previewed-alternative.tsx"),
  route(":locale/blog/previewed-alternative", "routes/blog.previewed-alternative.tsx", { id: "blog-previewed-alternative-locale" }),
  route("blog/butterkit-alternative", "routes/blog.butterkit-alternative.tsx"),
  route(":locale/blog/butterkit-alternative", "routes/blog.butterkit-alternative.tsx", { id: "blog-butterkit-alternative-locale" }),
  route("blog/shotbot-alternative", "routes/blog.shotbot-alternative.tsx"),
  route(":locale/blog/shotbot-alternative", "routes/blog.shotbot-alternative.tsx", { id: "blog-shotbot-alternative-locale" }),
  route("blog/publish-app-on-google-play", "routes/blog.publish-app-on-google-play.tsx"),
  route(":locale/blog/publish-app-on-google-play", "routes/blog.publish-app-on-google-play.tsx", { id: "blog-publish-app-on-google-play-locale" }),
  route("blog/google-play-promo-video", "routes/blog.google-play-promo-video.tsx"),
  route(":locale/blog/google-play-promo-video", "routes/blog.google-play-promo-video.tsx", { id: "blog-google-play-promo-video-locale" }),
  route("blog/app-store-description-that-converts", "routes/blog.app-store-description-that-converts.tsx"),
  route(":locale/blog/app-store-description-that-converts", "routes/blog.app-store-description-that-converts.tsx", { id: "blog-app-store-description-that-converts-locale" }),
  route("blog/app-store-keyword-research", "routes/blog.app-store-keyword-research.tsx"),
  route(":locale/blog/app-store-keyword-research", "routes/blog.app-store-keyword-research.tsx", { id: "blog-app-store-keyword-research-locale" }),
  route("blog/app-store-screenshots-for-games", "routes/blog.app-store-screenshots-for-games.tsx"),
  route(":locale/blog/app-store-screenshots-for-games", "routes/blog.app-store-screenshots-for-games.tsx", { id: "blog-app-store-screenshots-for-games-locale" }),
  route("blog/app-store-screenshots-for-fitness-apps", "routes/blog.app-store-screenshots-for-fitness-apps.tsx"),
  route(":locale/blog/app-store-screenshots-for-fitness-apps", "routes/blog.app-store-screenshots-for-fitness-apps.tsx", { id: "blog-app-store-screenshots-for-fitness-apps-locale" }),
  route("blog/change-app-store-screenshots-without-updating-app", "routes/blog.change-app-store-screenshots-without-updating-app.tsx"),
  route(":locale/blog/change-app-store-screenshots-without-updating-app", "routes/blog.change-app-store-screenshots-without-updating-app.tsx", { id: "blog-change-app-store-screenshots-without-updating-app-locale" }),
  route("blog/best-free-app-store-screenshot-generators", "routes/blog.best-free-app-store-screenshot-generators.tsx"),
  route(":locale/blog/best-free-app-store-screenshot-generators", "routes/blog.best-free-app-store-screenshot-generators.tsx", { id: "blog-best-free-app-store-screenshot-generators-locale" }),
  route("blog/mac-app-store-screenshot-sizes", "routes/blog.mac-app-store-screenshot-sizes.tsx"),
  route(":locale/blog/mac-app-store-screenshot-sizes", "routes/blog.mac-app-store-screenshot-sizes.tsx", { id: "blog-mac-app-store-screenshot-sizes-locale" }),
  route("blog/iphone-simulator-screenshots", "routes/blog.iphone-simulator-screenshots.tsx"),
  route(":locale/blog/iphone-simulator-screenshots", "routes/blog.iphone-simulator-screenshots.tsx", { id: "blog-iphone-simulator-screenshots-locale" }),
  route("blog/submit-app-to-app-store", "routes/blog.submit-app-to-app-store.tsx"),
  route(":locale/blog/submit-app-to-app-store", "routes/blog.submit-app-to-app-store.tsx", { id: "blog-submit-app-to-app-store-locale" }),
  route("blog/how-many-app-store-screenshots", "routes/blog.how-many-app-store-screenshots.tsx"),
  route(":locale/blog/how-many-app-store-screenshots", "routes/blog.how-many-app-store-screenshots.tsx", { id: "blog-how-many-app-store-screenshots-locale" }),
  route("blog/screenshot-generator-vs-figma-vs-photoshop", "routes/blog.screenshot-generator-vs-figma-vs-photoshop.tsx"),
  route(":locale/blog/screenshot-generator-vs-figma-vs-photoshop", "routes/blog.screenshot-generator-vs-figma-vs-photoshop.tsx", { id: "blog-screenshot-generator-vs-figma-vs-photoshop-locale" }),
  route("blog/localize-screenshots-japan-china-germany", "routes/blog.localize-screenshots-japan-china-germany.tsx"),
  route(":locale/blog/localize-screenshots-japan-china-germany", "routes/blog.localize-screenshots-japan-china-germany.tsx", { id: "blog-localize-screenshots-japan-china-germany-locale" }),
  route("blog/app-store-app-preview-video-specs", "routes/blog.app-store-app-preview-video-specs.tsx"),
  route(":locale/blog/app-store-app-preview-video-specs", "routes/blog.app-store-app-preview-video-specs.tsx", { id: "blog-app-store-app-preview-video-specs-locale" }),
  route("blog/device-mockup-generator-app-screenshots", "routes/blog.device-mockup-generator-app-screenshots.tsx"),
  route(":locale/blog/device-mockup-generator-app-screenshots", "routes/blog.device-mockup-generator-app-screenshots.tsx", { id: "blog-device-mockup-generator-app-screenshots-locale" }),
  route("blog/app-store-optimization-aso-guide", "routes/blog.app-store-optimization-aso-guide.tsx"),
  route(":locale/blog/app-store-optimization-aso-guide", "routes/blog.app-store-optimization-aso-guide.tsx", { id: "blog-app-store-optimization-aso-guide-locale" }),
  route("blog/app-icon-sizes-design-guidelines", "routes/blog.app-icon-sizes-design-guidelines.tsx"),
  route(":locale/blog/app-icon-sizes-design-guidelines", "routes/blog.app-icon-sizes-design-guidelines.tsx", { id: "blog-app-icon-sizes-design-guidelines-locale" }),
  route("blog/app-store-screenshot-examples", "routes/blog.app-store-screenshot-examples.tsx"),
  route(":locale/blog/app-store-screenshot-examples", "routes/blog.app-store-screenshot-examples.tsx", { id: "blog-app-store-screenshot-examples-locale" }),
  route("blog/google-play-feature-graphic-size-template-examples", "routes/blog.google-play-feature-graphic-size-template-examples.tsx"),
  route(":locale/blog/google-play-feature-graphic-size-template-examples", "routes/blog.google-play-feature-graphic-size-template-examples.tsx", { id: "blog-google-play-feature-graphic-size-template-examples-locale" }),
  route("blog/app-store-screenshots-rejected-fix", "routes/blog.app-store-screenshots-rejected-fix.tsx"),
  route(":locale/blog/app-store-screenshots-rejected-fix", "routes/blog.app-store-screenshots-rejected-fix.tsx", { id: "blog-app-store-screenshots-rejected-fix-locale" }),
  route("blog/google-play-screenshot-rejected-fix", "routes/blog.google-play-screenshot-rejected-fix.tsx"),
  route(":locale/blog/google-play-screenshot-rejected-fix", "routes/blog.google-play-screenshot-rejected-fix.tsx", { id: "blog-google-play-screenshot-rejected-fix-locale" }),
  route("blog/app-store-screenshot-order", "routes/blog.app-store-screenshot-order.tsx"),
  route(":locale/blog/app-store-screenshot-order", "routes/blog.app-store-screenshot-order.tsx", { id: "blog-app-store-screenshot-order-locale" }),
  route("blog/app-store-screenshot-copywriting-examples", "routes/blog.app-store-screenshot-copywriting-examples.tsx"),
  route(":locale/blog/app-store-screenshot-copywriting-examples", "routes/blog.app-store-screenshot-copywriting-examples.tsx", { id: "blog-app-store-screenshot-copywriting-examples-locale" }),
  route("blog/app-store-screenshot-mistakes", "routes/blog.app-store-screenshot-mistakes.tsx"),
  route(":locale/blog/app-store-screenshot-mistakes", "routes/blog.app-store-screenshot-mistakes.tsx", { id: "blog-app-store-screenshot-mistakes-locale" }),
  route("blog/iphone-ipad-app-store-screenshots", "routes/blog.iphone-ipad-app-store-screenshots.tsx"),
  route(":locale/blog/iphone-ipad-app-store-screenshots", "routes/blog.iphone-ipad-app-store-screenshots.tsx", { id: "blog-iphone-ipad-app-store-screenshots-locale" }),
  route("blog/google-play-store-listing-graphics-checklist", "routes/blog.google-play-store-listing-graphics-checklist.tsx"),
  route(":locale/blog/google-play-store-listing-graphics-checklist", "routes/blog.google-play-store-listing-graphics-checklist.tsx", { id: "blog-google-play-store-listing-graphics-checklist-locale" }),
  route("blog/seasonal-app-store-screenshots", "routes/blog.seasonal-app-store-screenshots.tsx"),
  route(":locale/blog/seasonal-app-store-screenshots", "routes/blog.seasonal-app-store-screenshots.tsx", { id: "blog-seasonal-app-store-screenshots-locale" }),
  route("blog/app-store-screenshot-localization-guide", "routes/blog.app-store-screenshot-localization-guide.tsx"),
  route(":locale/blog/app-store-screenshot-localization-guide", "routes/blog.app-store-screenshot-localization-guide.tsx", { id: "blog-app-store-screenshot-localization-guide-locale" }),
  route("blog/popular-figma-templates-app-store-screenshots-device-mockups", "routes/blog.popular-figma-templates-app-store-screenshots-device-mockups.tsx"),
  route(":locale/blog/popular-figma-templates-app-store-screenshots-device-mockups", "routes/blog.popular-figma-templates-app-store-screenshots-device-mockups.tsx", { id: "blog-popular-figma-templates-app-store-screenshots-device-mockups-locale" }),
  route("blog/app-store-screenshot-designers-creators-to-follow", "routes/blog.app-store-screenshot-designers-creators-to-follow.tsx"),
  route(":locale/blog/app-store-screenshot-designers-creators-to-follow", "routes/blog.app-store-screenshot-designers-creators-to-follow.tsx", { id: "blog-app-store-screenshot-designers-creators-to-follow-locale" }),
  route("blog/google-play-screenshot-sizes-requirements", "routes/blog.google-play-screenshot-sizes-requirements.tsx"),
  route(":locale/blog/google-play-screenshot-sizes-requirements", "routes/blog.google-play-screenshot-sizes-requirements.tsx", { id: "blog-google-play-screenshot-sizes-requirements-locale" }),
  route("blog/ab-test-app-store-screenshots", "routes/blog.ab-test-app-store-screenshots.tsx"),
  route(":locale/blog/ab-test-app-store-screenshots", "routes/blog.ab-test-app-store-screenshots.tsx", { id: "blog-ab-test-app-store-screenshots-locale" }),
  route("blog/custom-product-pages-app-store-screenshots", "routes/blog.custom-product-pages-app-store-screenshots.tsx"),
  route(":locale/blog/custom-product-pages-app-store-screenshots", "routes/blog.custom-product-pages-app-store-screenshots.tsx", { id: "blog-custom-product-pages-app-store-screenshots-locale" }),
  route("blog/design-app-store-screenshots-in-figma", "routes/blog.design-app-store-screenshots-in-figma.tsx"),
  route(":locale/blog/design-app-store-screenshots-in-figma", "routes/blog.design-app-store-screenshots-in-figma.tsx", { id: "blog-design-app-store-screenshots-in-figma-locale" }),
  route("blog/best-app-store-screenshot-tools", "routes/blog.best-app-store-screenshot-tools.tsx"),
  route(":locale/blog/best-app-store-screenshot-tools", "routes/blog.best-app-store-screenshot-tools.tsx", { id: "blog-best-app-store-screenshot-tools-locale" }),
  route("blog/make-and-ship-screenshots-with-fastlane", "routes/blog.make-and-ship-screenshots-with-fastlane.tsx"),
  route(":locale/blog/make-and-ship-screenshots-with-fastlane", "routes/blog.make-and-ship-screenshots-with-fastlane.tsx", { id: "blog-make-and-ship-screenshots-with-fastlane-locale" }),
  route("blog/upload-screenshots-to-app-store-connect", "routes/blog.upload-screenshots-to-app-store-connect.tsx"),
  route(":locale/blog/upload-screenshots-to-app-store-connect", "routes/blog.upload-screenshots-to-app-store-connect.tsx", { id: "blog-upload-screenshots-to-app-store-connect-locale" }),
  route("blog/screenshot-sizes-app-store-google-play", "routes/blog.screenshot-sizes-app-store-google-play.tsx"),
  route(":locale/blog/screenshot-sizes-app-store-google-play", "routes/blog.screenshot-sizes-app-store-google-play.tsx", { id: "blog-screenshot-sizes-app-store-google-play-locale" }),
  route("blog/app-store-screenshot-sizes", "routes/blog.app-store-screenshot-sizes.tsx"),
  route(":locale/blog/app-store-screenshot-sizes", "routes/blog.app-store-screenshot-sizes.tsx", { id: "blog-app-store-screenshot-sizes-locale" }),
  route("blog/screenshots-that-convert", "routes/blog.screenshots-that-convert.tsx"),
  route(":locale/blog/screenshots-that-convert", "routes/blog.screenshots-that-convert.tsx", { id: "blog-screenshots-that-convert-locale" }),
  route("blog/localize-app-store-screenshots", "routes/blog.localize-app-store-screenshots.tsx"),
  route(":locale/blog/localize-app-store-screenshots", "routes/blog.localize-app-store-screenshots.tsx", { id: "blog-localize-app-store-screenshots-locale" }),
  route("docs", "routes/docs._index.tsx"),
  route(":locale/docs", "routes/docs._index.tsx", { id: "docs-index-locale" }),
  route("docs/help", "routes/docs.help.tsx"),
  route(":locale/docs/help", "routes/docs.help.tsx", { id: "docs-help-locale" }),
  route("docs/project-schema", "routes/docs.project-schema.tsx"),
  route(":locale/docs/project-schema", "routes/docs.project-schema.tsx", { id: "docs-project-schema-locale" }),
  route("vs", "routes/vs._index.tsx"),
  route(":locale/vs", "routes/vs._index.tsx", { id: "vs-index-locale" }),
  route("vs/fastlane-snapshot", "routes/vs.fastlane-snapshot.tsx"),
  route(":locale/vs/fastlane-snapshot", "routes/vs.fastlane-snapshot.tsx", { id: "vs-fastlane-snapshot-locale" }),
  route("vs/screenshot-studio", "routes/vs.screenshot-studio.tsx"),
  route(":locale/vs/screenshot-studio", "routes/vs.screenshot-studio.tsx", { id: "vs-screenshot-studio-locale" }),
  route("vs/butterkit", "routes/vs.butterkit.tsx"),
  route(":locale/vs/butterkit", "routes/vs.butterkit.tsx", { id: "vs-butterkit-locale" }),
  route("vs/shotbot", "routes/vs.shotbot.tsx"),
  route(":locale/vs/shotbot", "routes/vs.shotbot.tsx", { id: "vs-shotbot-locale" }),
  route("vs/rotato", "routes/vs.rotato.tsx"),
  route(":locale/vs/rotato", "routes/vs.rotato.tsx", { id: "vs-rotato-locale" }),
  route("vs/applaunchpad", "routes/vs.applaunchpad.tsx"),
  route(":locale/vs/applaunchpad", "routes/vs.applaunchpad.tsx", { id: "vs-applaunchpad-locale" }),
  route("vs/previewed", "routes/vs.previewed.tsx"),
  route(":locale/vs/previewed", "routes/vs.previewed.tsx", { id: "vs-previewed-locale" }),
  route("vs/appscreens", "routes/vs.appscreens.tsx"),
  route(":locale/vs/appscreens", "routes/vs.appscreens.tsx", { id: "vs-appscreens-locale" }),
  route("vs/appmockup-studio", "routes/vs.appmockup-studio.tsx"),
  route(":locale/vs/appmockup-studio", "routes/vs.appmockup-studio.tsx", { id: "vs-appmockup-studio-locale" }),
  route("vs/screenshots-pro", "routes/vs.screenshots-pro.tsx"),
  route(":locale/vs/screenshots-pro", "routes/vs.screenshots-pro.tsx", { id: "vs-screenshots-pro-locale" }),
  route("vs/mockuuups-studio", "routes/vs.mockuuups-studio.tsx"),
  route(":locale/vs/mockuuups-studio", "routes/vs.mockuuups-studio.tsx", { id: "vs-mockuuups-studio-locale" }),
  route("vs/placeit", "routes/vs.placeit.tsx"),
  route(":locale/vs/placeit", "routes/vs.placeit.tsx", { id: "vs-placeit-locale" }),
  route("friends", "routes/friends.tsx"),
  route("sitemap.xml", "routes/sitemap[.]xml.tsx"),
  route("llms.txt", "routes/llms[.]txt.tsx"),
  route(":locale", "routes/localized-home.tsx"),
  route("*", "routes/$.tsx"),
] satisfies RouteConfig;
