import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("privacy", "routes/privacy.tsx"),
  route(":locale/privacy", "routes/privacy.tsx", { id: "privacy-locale" }),
  route("terms", "routes/terms.tsx"),
  route(":locale/terms", "routes/terms.tsx", { id: "terms-locale" }),
  route("changelog", "routes/changelog.tsx"),
  route(":locale/changelog", "routes/changelog.tsx", { id: "changelog-locale" }),
  route("support", "routes/support.tsx"),
  route("download", "routes/download.tsx"),
  route("buy", "routes/buy.tsx"),
  route("pricing", "routes/pricing.tsx"),
  route("features", "routes/features.tsx"),
  route("templates", "routes/templates.tsx"),
  route("press", "routes/press.tsx"),
  route("thanks", "routes/thanks.tsx"),
  route(":locale/support", "routes/support.tsx", { id: "support-locale" }),
  route("tutorials", "routes/tutorials.tsx"),
  route(":locale/tutorials", "routes/tutorials.tsx", { id: "tutorials-locale" }),
  route(
    "tutorials/how-to-use-screenshot-bro",
    "routes/tutorials.how-to-use-screenshot-bro.tsx",
  ),
  route(
    ":locale/tutorials/how-to-use-screenshot-bro",
    "routes/tutorials.how-to-use-screenshot-bro.tsx",
    { id: "tutorials-how-to-use-screenshot-bro-locale" },
  ),
  route("blog", "routes/blog._index.tsx"),
  route(":locale/blog", "routes/blog._index.tsx", { id: "blog-locale" }),
  // Posts are English-only. Every /{locale}/blog/<slug> 301s to /blog/<slug>
  // instead of serving the English body again under a locale prefix.
  route(":locale/blog/:slug", "routes/blog.locale-redirect.tsx"),
  route("blog/iphone-duo-app-store-screenshots", "routes/blog.iphone-duo-app-store-screenshots.tsx"),
  route("blog/googlebook-google-play-screenshots", "routes/blog.googlebook-google-play-screenshots.tsx"),
  route("blog/app-store-creative-assets", "routes/blog.app-store-creative-assets.tsx"),
  route("blog/screenshot-bro-mcp-server", "routes/blog.screenshot-bro-mcp-server.tsx"),
  route("blog/best-app-store-screenshot-tools-for-mac", "routes/blog.best-app-store-screenshot-tools-for-mac.tsx"),
  route("blog/best-app-screenshot-localization-tools", "routes/blog.best-app-screenshot-localization-tools.tsx"),
  route("blog/best-google-play-screenshot-tools", "routes/blog.best-google-play-screenshot-tools.tsx"),
  route("blog/screenshot-bro-alternatives", "routes/blog.screenshot-bro-alternatives.tsx"),
  route("blog/appscreens-alternative", "routes/blog.appscreens-alternative.tsx"),
  route("blog/screenshots-pro-alternative", "routes/blog.screenshots-pro-alternative.tsx"),
  route("blog/rotato-alternative", "routes/blog.rotato-alternative.tsx"),
  route("blog/placeit-alternative", "routes/blog.placeit-alternative.tsx"),
  route("blog/mockuuups-studio-alternative", "routes/blog.mockuuups-studio-alternative.tsx"),
  route("blog/canva-app-store-screenshots", "routes/blog.canva-app-store-screenshots.tsx"),
  route("blog/appmockup-alternative", "routes/blog.appmockup-alternative.tsx"),
  route("blog/screenshot-studio-alternative", "routes/blog.screenshot-studio-alternative.tsx"),
  route("blog/applaunchpad-alternative", "routes/blog.applaunchpad-alternative.tsx"),
  route("blog/previewed-alternative", "routes/blog.previewed-alternative.tsx"),
  route("blog/butterkit-alternative", "routes/blog.butterkit-alternative.tsx"),
  route("blog/shotbot-alternative", "routes/blog.shotbot-alternative.tsx"),
  route("blog/publish-app-on-google-play", "routes/blog.publish-app-on-google-play.tsx"),
  route("blog/google-play-promo-video", "routes/blog.google-play-promo-video.tsx"),
  route("blog/app-store-description-that-converts", "routes/blog.app-store-description-that-converts.tsx"),
  route("blog/app-store-keyword-research", "routes/blog.app-store-keyword-research.tsx"),
  route("blog/app-store-screenshots-for-games", "routes/blog.app-store-screenshots-for-games.tsx"),
  route("blog/app-store-screenshots-for-fitness-apps", "routes/blog.app-store-screenshots-for-fitness-apps.tsx"),
  route("blog/change-app-store-screenshots-without-updating-app", "routes/blog.change-app-store-screenshots-without-updating-app.tsx"),
  route("blog/best-free-app-store-screenshot-generators", "routes/blog.best-free-app-store-screenshot-generators.tsx"),
  route("blog/mac-app-store-screenshot-sizes", "routes/blog.mac-app-store-screenshot-sizes.tsx"),
  route("blog/iphone-simulator-screenshots", "routes/blog.iphone-simulator-screenshots.tsx"),
  route("blog/submit-app-to-app-store", "routes/blog.submit-app-to-app-store.tsx"),
  route("blog/how-many-app-store-screenshots", "routes/blog.how-many-app-store-screenshots.tsx"),
  route("blog/screenshot-generator-vs-figma-vs-photoshop", "routes/blog.screenshot-generator-vs-figma-vs-photoshop.tsx"),
  route("blog/localize-screenshots-japan-china-germany", "routes/blog.localize-screenshots-japan-china-germany.tsx"),
  route("blog/app-store-app-preview-video-specs", "routes/blog.app-store-app-preview-video-specs.tsx"),
  route("blog/device-mockup-generator-app-screenshots", "routes/blog.device-mockup-generator-app-screenshots.tsx"),
  route("blog/app-store-optimization-aso-guide", "routes/blog.app-store-optimization-aso-guide.tsx"),
  route("blog/app-icon-sizes-design-guidelines", "routes/blog.app-icon-sizes-design-guidelines.tsx"),
  route("blog/app-store-screenshot-examples", "routes/blog.app-store-screenshot-examples.tsx"),
  route("blog/google-play-feature-graphic-size-template-examples", "routes/blog.google-play-feature-graphic-size-template-examples.tsx"),
  route("blog/app-store-screenshots-rejected-fix", "routes/blog.app-store-screenshots-rejected-fix.tsx"),
  route("blog/google-play-screenshot-rejected-fix", "routes/blog.google-play-screenshot-rejected-fix.tsx"),
  route("blog/app-store-screenshot-order", "routes/blog.app-store-screenshot-order.tsx"),
  route("blog/app-store-screenshot-copywriting-examples", "routes/blog.app-store-screenshot-copywriting-examples.tsx"),
  route("blog/app-store-screenshot-mistakes", "routes/blog.app-store-screenshot-mistakes.tsx"),
  route("blog/iphone-ipad-app-store-screenshots", "routes/blog.iphone-ipad-app-store-screenshots.tsx"),
  route("blog/google-play-store-listing-graphics-checklist", "routes/blog.google-play-store-listing-graphics-checklist.tsx"),
  route("blog/seasonal-app-store-screenshots", "routes/blog.seasonal-app-store-screenshots.tsx"),
  route("blog/app-store-screenshot-localization-guide", "routes/blog.app-store-screenshot-localization-guide.tsx"),
  route("blog/popular-figma-templates-app-store-screenshots-device-mockups", "routes/blog.popular-figma-templates-app-store-screenshots-device-mockups.tsx"),
  route("blog/app-store-screenshot-designers-creators-to-follow", "routes/blog.app-store-screenshot-designers-creators-to-follow.tsx"),
  route("blog/google-play-screenshot-sizes-requirements", "routes/blog.google-play-screenshot-sizes-requirements.tsx"),
  route("blog/ab-test-app-store-screenshots", "routes/blog.ab-test-app-store-screenshots.tsx"),
  route("blog/custom-product-pages-app-store-screenshots", "routes/blog.custom-product-pages-app-store-screenshots.tsx"),
  route("blog/design-app-store-screenshots-in-figma", "routes/blog.design-app-store-screenshots-in-figma.tsx"),
  route("blog/best-app-store-screenshot-tools", "routes/blog.best-app-store-screenshot-tools.tsx"),
  route("blog/make-and-ship-screenshots-with-fastlane", "routes/blog.make-and-ship-screenshots-with-fastlane.tsx"),
  route("blog/upload-screenshots-to-app-store-connect", "routes/blog.upload-screenshots-to-app-store-connect.tsx"),
  route("blog/screenshot-sizes-app-store-google-play", "routes/blog.screenshot-sizes-app-store-google-play.tsx"),
  route("blog/app-store-screenshot-sizes", "routes/blog.app-store-screenshot-sizes.tsx"),
  route("blog/screenshots-that-convert", "routes/blog.screenshots-that-convert.tsx"),
  route("blog/localize-app-store-screenshots", "routes/blog.localize-app-store-screenshots.tsx"),
  route("docs", "routes/docs._index.tsx"),
  route(":locale/docs", "routes/docs._index.tsx", { id: "docs-index-locale" }),
  route("docs/help", "routes/docs.help.tsx"),
  route(":locale/docs/help", "routes/docs.help.tsx", { id: "docs-help-locale" }),
  route("docs/project-schema", "routes/docs.project-schema.tsx"),
  route(":locale/docs/project-schema", "routes/docs.project-schema.tsx", { id: "docs-project-schema-locale" }),
  route("vs", "routes/vs._index.tsx"),
  route(":locale/vs", "routes/vs._index.tsx", { id: "vs-index-locale" }),
  route("vs/fastlane-snapshot", "routes/vs.fastlane-snapshot.tsx"),
  route(":locale/vs/fastlane-snapshot", "routes/vs.fastlane-snapshot.tsx", { id: "vs-fastlane-snapshot-locale" }),
  route("vs/screenshot-studio", "routes/vs.screenshot-studio.tsx"),
  route(":locale/vs/screenshot-studio", "routes/vs.screenshot-studio.tsx", { id: "vs-screenshot-studio-locale" }),
  route("vs/butterkit", "routes/vs.butterkit.tsx"),
  route(":locale/vs/butterkit", "routes/vs.butterkit.tsx", { id: "vs-butterkit-locale" }),
  route("vs/shotbot", "routes/vs.shotbot.tsx"),
  route(":locale/vs/shotbot", "routes/vs.shotbot.tsx", { id: "vs-shotbot-locale" }),
  route("vs/rotato", "routes/vs.rotato.tsx"),
  route(":locale/vs/rotato", "routes/vs.rotato.tsx", { id: "vs-rotato-locale" }),
  route("vs/applaunchpad", "routes/vs.applaunchpad.tsx"),
  route(":locale/vs/applaunchpad", "routes/vs.applaunchpad.tsx", { id: "vs-applaunchpad-locale" }),
  route("vs/previewed", "routes/vs.previewed.tsx"),
  route(":locale/vs/previewed", "routes/vs.previewed.tsx", { id: "vs-previewed-locale" }),
  route("vs/appscreens", "routes/vs.appscreens.tsx"),
  route(":locale/vs/appscreens", "routes/vs.appscreens.tsx", { id: "vs-appscreens-locale" }),
  route("vs/appmockup-studio", "routes/vs.appmockup-studio.tsx"),
  route(":locale/vs/appmockup-studio", "routes/vs.appmockup-studio.tsx", { id: "vs-appmockup-studio-locale" }),
  route("vs/screenshots-pro", "routes/vs.screenshots-pro.tsx"),
  route(":locale/vs/screenshots-pro", "routes/vs.screenshots-pro.tsx", { id: "vs-screenshots-pro-locale" }),
  route("vs/mockuuups-studio", "routes/vs.mockuuups-studio.tsx"),
  route(":locale/vs/mockuuups-studio", "routes/vs.mockuuups-studio.tsx", { id: "vs-mockuuups-studio-locale" }),
  route("vs/placeit", "routes/vs.placeit.tsx"),
  route(":locale/vs/placeit", "routes/vs.placeit.tsx", { id: "vs-placeit-locale" }),
  route("friends", "routes/friends.tsx"),
  route("sitemap.xml", "routes/sitemap[.]xml.tsx"),
  route("llms.txt", "routes/llms[.]txt.tsx"),
  route(":locale", "routes/localized-home.tsx"),
  route("*", "routes/$.tsx"),
] satisfies RouteConfig;
