import type { Route } from "./+types/blog.screenshots-pro-alternative";
import { BlogArticleShell } from "~/components/BlogArticleShell";
import { buildBlogPostLinks, buildBlogPostMeta } from "~/config/blog-seo";
import type { LocaleCode } from "~/config/localization";
import { useLoaderData } from "react-router";

const SLUG = "screenshots-pro-alternative";

const COMPARISON = [
  {
    factor: "Platform",
    screenshotsPro: "Browser-based with cloud storage and auto-save",
    screenshotBro: "Native Mac and iPad app, files on your machine",
  },
  {
    factor: "Pricing model",
    screenshotsPro: "Free Basic plan, paid monthly plans above it",
    screenshotBro: "Free tier with watermark-free exports, paid Pro unlock",
  },
  {
    factor: "Automation",
    screenshotsPro: "REST API for CI/CD on the top plan",
    screenshotBro: "No API — direct App Store Connect upload from the app",
  },
  {
    factor: "3D perspective",
    screenshotsPro: "3D angles on paid plans, clay and real frames",
    screenshotBro: "Flat device frames for iPhone, iPad, Mac, and Android",
  },
  {
    factor: "Localization",
    screenshotsPro: "Auto-translate on paid plans",
    screenshotBro: "30 language presets, on-device auto-translate, per-shape overrides",
  },
  {
    factor: "Store upload",
    screenshotsPro: "Export files, upload yourself",
    screenshotBro: "Direct App Store Connect upload on Pro",
  },
] as const;

export async function loader() {
  return { locale: "en" as LocaleCode };
}

export const meta: Route.MetaFunction = ({ matches }) =>
  buildBlogPostMeta(SLUG, matches, "en");

export const links: Route.LinksFunction = () => buildBlogPostLinks(SLUG);

export default function BlogPost() {
  const { locale } = useLoaderData<typeof loader>();

  return (
    <BlogArticleShell
      slug={SLUG}
      locale={locale}
      tldr="Screenshots Pro is a browser tool with a free Basic plan and an API for CI/CD pipelines; Screenshot Bro is a native Mac and iPad editor that uploads finished sets straight to App Store Connect. Pick by whether you want screenshots scripted or designed."
      ctaMessage="Prefer designing screenshots in a native editor instead of scripting them? Try Screenshot Bro free."
      seoLinks={[
        {
          href: "/vs/fastlane-snapshot",
          label: "Fastlane snapshot vs Screenshot Bro",
          description: "the other half of the automation question.",
        },
        {
          href: "/blog/make-and-ship-screenshots-with-fastlane",
          label: "Ship screenshots with Fastlane",
          description: "automating capture and delivery end to end.",
        },
        {
          href: "/blog/best-app-store-screenshot-tools-for-mac",
          label: "Best tools for Mac",
          description: "native options compared side by side.",
        },
      ]}
      faqs={[
        {
          question: "Is Screenshots Pro free?",
          answer:
            "Screenshots Pro lists a free Basic plan alongside paid monthly plans; at the time of checking, the paid tiers were the ones carrying 3D angles, custom fonts, localization, and API access. Pricing changes, so check screenshots.pro for the current plans and limits.",
        },
        {
          question: "What is a good Screenshots Pro alternative?",
          answer:
            "If you want a native Mac and iPad editor rather than a browser tool — with multi-row layouts, 30 language presets, watermark-free exports on the free tier, and direct App Store Connect upload — Screenshot Bro is a strong alternative. If what you actually want is scripted screenshots in CI, Fastlane snapshot plus frameit is the closer match.",
        },
        {
          question: "Does Screenshot Bro have an API?",
          answer:
            "No. Screenshot Bro is a native app you design in, and it uploads finished sets to App Store Connect for you. If you need screenshots regenerated by a build server on every release, use Fastlane snapshot or a tool with a REST API, and treat Screenshot Bro as the design layer above the raw captures.",
        },
      ]}
    >
      <p>
        Screenshots Pro is a capable browser-based generator with pixel-perfect
        device frames, smart export to every store size, and — on its top plan —
        a REST API you can call from CI. This page is for people searching for a{" "}
        <strong>Screenshots Pro alternative</strong>, usually because they want a
        native editor, deeper localization control, or upload straight to App
        Store Connect rather than a folder of exported files.
      </p>
      <p>
        Competitor details below were checked in August 2026 on the Screenshots
        Pro site; pricing and features change, so verify there before deciding.
      </p>

      <h2>What Screenshots Pro Does Well</h2>
      <p>
        The API is the real differentiator: if screenshots should be regenerated
        by a pipeline rather than a person, very few design tools offer that at
        all. Beyond it, Screenshots Pro covers a large set of current devices in
        both clay and realistic frames, offers 3D perspective angles on paid
        plans, auto-resizes one design into every required App Store and Google
        Play size, and keeps everything in the cloud with auto-save — convenient
        when several people touch the same listing.
      </p>

      <h2>Why People Look for an Alternative</h2>
      <ul>
        <li>
          They want a <strong>native Mac or iPad app</strong> that works offline
          and keeps project files locally rather than in an account.
        </li>
        <li>
          They want <strong>localization without a monthly plan</strong> — 30
          presets, auto-translate, and per-shape overrides included.
        </li>
        <li>
          They want the tool to <strong>upload to App Store Connect</strong>{" "}
          instead of exporting a folder and dragging files in by hand.
        </li>
      </ul>

      <h2>Screenshots Pro vs Screenshot Bro</h2>
      <table>
        <thead>
          <tr>
            <th>Factor</th>
            <th>Screenshots Pro</th>
            <th>Screenshot Bro</th>
          </tr>
        </thead>
        <tbody>
          {COMPARISON.map((row) => (
            <tr key={row.factor}>
              <td>{row.factor}</td>
              <td>{row.screenshotsPro}</td>
              <td>{row.screenshotBro}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <h2>Who Should Pick Which</h2>
      <p>
        Choose <strong>Screenshots Pro</strong> if screenshots should be produced
        by a script, if you need 3D angles, or if your team works across
        operating systems in a shared cloud project. Choose{" "}
        <strong>Screenshot Bro</strong> if you design screenshots by hand on a
        Mac or iPad, want a watermark-free free tier, and want the finished set
        pushed to App Store Connect from the same app. If you are weighing
        automation more broadly, read{" "}
        <a href="/vs/fastlane-snapshot">Fastlane snapshot vs Screenshot Bro</a>.
      </p>
    </BlogArticleShell>
  );
}
