import type { Route } from "./+types/blog.best-app-store-screenshot-tools-for-mac";
import { BlogArticleShell } from "~/components/BlogArticleShell";
import { buildBlogPostLinks, buildBlogPostMeta } from "~/config/blog-seo";
import type { LocaleCode } from "~/config/localization";
import { useLoaderData } from "react-router";

const SLUG = "best-app-store-screenshot-tools-for-mac";

const TOOLS = [
  {
    tool: "Screenshot Bro",
    type: "Native Mac, iPad and iPhone app",
    free: "Watermark-free exports on the free tier",
    localization: "81 presets, on-device auto-translate",
    upload: "Direct App Store Connect and Google Play upload, free tier included",
  },
  {
    tool: "Screenshot Studio",
    type: "Native Mac and iOS app",
    free: "Free to try; payment required to export",
    localization: "AI translation, any language",
    upload: "Direct App Store Connect upload",
  },
  {
    tool: "Rotato",
    type: "Native Mac app (web beta)",
    free: "Unlimited free trial",
    localization: "Not a built-in workflow",
    upload: "Export files, upload yourself",
  },
  {
    tool: "Fastlane frameit",
    type: "Command line on macOS",
    free: "Free and open source",
    localization: "Titles from .strings files per locale",
    upload: "Yes, via fastlane deliver",
  },
  {
    tool: "Mockuuups Studio",
    type: "Desktop app plus web and plugins",
    free: "Free tier, paid plans above it",
    localization: "Not a built-in workflow",
    upload: "Export files, upload yourself",
  },
  {
    tool: "Figma or Sketch",
    type: "Native or desktop design tool",
    free: "Free tier (Figma), paid licence (Sketch)",
    localization: "Manual, or via plugins",
    upload: "Export files, upload yourself",
  },
] as const;

export async function loader() {
  return { locale: "en" as LocaleCode };
}

export const meta: Route.MetaFunction = ({ matches }) =>
  buildBlogPostMeta(SLUG, matches, "en");

export const links: Route.LinksFunction = () => buildBlogPostLinks(SLUG);

export default function BlogPost() {
  const { locale } = useLoaderData<typeof loader>();

  return (
    <BlogArticleShell
      slug={SLUG}
      locale={locale}
      tldr="Most App Store screenshot generators are browser tools. If you specifically want a Mac app — offline, fast, files on disk — the real options are Screenshot Bro, Screenshot Studio, Rotato, Fastlane frameit on the command line, and general design tools like Figma or Sketch."
      ctaMessage="Screenshot Bro is a native Mac, iPad and iPhone app with a watermark-free free tier. Try it free."
      ctaHomeLinkLabel="the native Mac App Store screenshot tool"
      seoLinks={[
        {
          href: "/blog/best-free-app-store-screenshot-generators",
          label: "Best free generators",
          description: "the free options, browser tools included.",
        },
        {
          href: "/blog/mac-app-store-screenshot-sizes",
          label: "Mac App Store sizes",
          description: "the exact dimensions for a Mac app listing.",
        },
        {
          href: "/blog/screenshot-generator-vs-figma-vs-photoshop",
          label: "Generator vs Figma vs Photoshop",
          description: "whether a dedicated tool is worth it at all.",
        },
      ]}
      faqs={[
        {
          question: "What is the best App Store screenshot tool for Mac?",
          answer:
            "For a native Mac app that handles the whole listing — device frames, multi-row layouts, localization, batch export, and upload — Screenshot Bro and Screenshot Studio are the two purpose-built options. Rotato is the pick if you also need 3D renders and video, and Fastlane frameit is the pick if screenshots should be generated by a script instead of a person.",
        },
        {
          question: "Why use a native Mac app instead of a browser screenshot generator?",
          answer:
            "Native apps work offline, keep large image files on local disk instead of uploading them, feel faster on a big canvas, and integrate with Finder and iCloud. Browser tools win on portability — they run on any operating system and need no install — so the choice mostly comes down to whether you work on a Mac full time.",
        },
        {
          question: "Do any Mac screenshot tools upload to App Store Connect directly?",
          answer:
            "Yes. Screenshot Bro uploads directly to App Store Connect and Google Play on every tier, free included, Screenshot Studio uploads directly, and Fastlane can deliver screenshots via fastlane deliver. Most browser-based generators export a folder of files that you upload by hand.",
        },
      ]}
    >
      <p>
        Search for an App Store screenshot generator and you will mostly find
        browser tools. This roundup covers the narrower question:{" "}
        <strong>the best App Store screenshot tools for Mac</strong> — apps that
        run locally, work offline, and keep your project files on your own disk.
        It is written by the maker of one of them, so the comparison points below
        are factual and checkable rather than scored.
      </p>
      <p>
        Details were checked in August 2026 against each tool&apos;s own site;
        pricing and features change, so verify before deciding.
      </p>

      <h2>How To Choose</h2>
      <ul>
        <li>
          <strong>Does it cover every size you ship?</strong> iPhone, iPad, and
          Mac listings all need different dimensions.
        </li>
        <li>
          <strong>Does localization exist as a workflow?</strong> Ten markets by
          hand is ten times the work.
        </li>
        <li>
          <strong>Can you export before paying?</strong> Free tiers differ: some
          watermark, some block export entirely.
        </li>
        <li>
          <strong>Does it upload?</strong> Direct App Store Connect upload
          removes the most annoying step of a release.
        </li>
      </ul>

      <h2>The Options</h2>

      <h3>Screenshot Bro — native, watermark-free free tier</h3>
      <p>
        A Mac, iPad and iPhone app built around one continuous canvas: every device size,
        row, and locale side by side. Device frames for iPhone, iPad, Mac, and
        Android, text, shapes, gradients and SVG, 81 language presets with
        on-device auto-translate and per-shape overrides, batch export organized
        by locale and row, and direct App Store Connect and Google Play upload. The free
        tier exports without a watermark (1 project, 3 rows, 5 templates per row).
        Projects are <a href="/docs/project-schema">plain JSON files</a>.
      </p>

      <h3>Screenshot Studio — widest Apple device coverage</h3>
      <p>
        A native Mac and iOS app covering iPhone, iPad, Mac, Apple Watch, Apple
        TV, Apple Vision Pro, and Android phones, with built-in AI translation
        into any language and direct App Store Connect upload. All features are
        free to try; payment is required to export. If you ship a Watch or Vision
        Pro app, it covers device classes most tools skip. See the{" "}
        <a href="/blog/screenshot-studio-alternative">head-to-head comparison</a>.
      </p>

      <h3>Rotato — 3D mockups and video</h3>
      <p>
        A native Mac app (with a web version in beta) for 3D device mockups and
        animated product movies, sold as a one-time purchase with an unlimited
        free trial. It ships App Store templates and supports app previews, but
        it is not built around fanning one design across every size and language.
        Details in the <a href="/blog/rotato-alternative">Rotato comparison</a>.
      </p>

      <h3>Fastlane frameit — free, scripted, no design tool</h3>
      <p>
        Part of the open-source Fastlane toolchain: capture with snapshot, frame
        with frameit, add localized titles from .strings files, deliver with
        fastlane deliver. Free, reproducible, and CI-friendly — but the design
        ceiling is low and the setup cost is real. See{" "}
        <a href="/vs/fastlane-snapshot">Fastlane snapshot vs Screenshot Bro</a>.
      </p>

      <h3>Mockuuups Studio — a mockup library, not a listing tool</h3>
      <p>
        A desktop app (plus web and plugins for Figma, Sketch, Adobe Express, and
        Penpot) with over 5,300 mockups. Excellent for presentation images, less
        suited to a full localized store set — see the{" "}
        <a href="/blog/mockuuups-studio-alternative">comparison</a>.
      </p>

      <h3>Figma or Sketch — full control, full manual work</h3>
      <p>
        If you already design in Figma or Sketch, you can build screenshots there
        with complete freedom over layout. You take on the repetition yourself:
        every size, every locale, every release. Our{" "}
        <a href="/blog/design-app-store-screenshots-in-figma">
          Figma screenshot guide
        </a>{" "}
        covers how to make that manageable.
      </p>

      <h2>Comparison Table</h2>
      <table>
        <thead>
          <tr>
            <th>Tool</th>
            <th>Type</th>
            <th>Free tier</th>
            <th>Localization</th>
            <th>Store upload</th>
          </tr>
        </thead>
        <tbody>
          {TOOLS.map((row) => (
            <tr key={row.tool}>
              <td>{row.tool}</td>
              <td>{row.type}</td>
              <td>{row.free}</td>
              <td>{row.localization}</td>
              <td>{row.upload}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <h2>The Short Version</h2>
      <p>
        Ship on iPhone, iPad, or Mac and want the whole listing handled locally:{" "}
        <strong>Screenshot Bro</strong>. Ship on Apple Watch, TV, or Vision Pro:{" "}
        <strong>Screenshot Studio</strong>. Need a launch video:{" "}
        <strong>Rotato</strong>. Want screenshots regenerated by CI:{" "}
        <strong>Fastlane</strong>. Already living in a design tool:{" "}
        <strong>Figma or Sketch</strong>. For browser-based options, see the{" "}
        <a href="/blog/best-free-app-store-screenshot-generators">
          free generators roundup
        </a>{" "}
        and the <a href="/vs">full comparison hub</a>, which has a head-to-head
        page for each native tool here:{" "}
        <a href="/vs/screenshot-studio">Screenshot Studio</a>,{" "}
        <a href="/vs/rotato">Rotato</a> and{" "}
        <a href="/vs/mockuuups-studio">Mockuuups Studio</a>.
      </p>
    </BlogArticleShell>
  );
}
