import { isLocaleCode, type LocaleCode } from "~/config/localization";
import { data, useLoaderData } from "react-router";
import type { Route } from "./+types/vs.fastlane-snapshot";
import {
  ComparisonShell,
  ComparisonTable,
  type ComparisonRow,
  type RelatedLink,
} from "~/components/ComparisonShell";
import type { BlogFaqItem } from "~/config/blog-seo";
import { buildComparisonMeta } from "~/config/comparison-seo";
import { SCREENSHOT_BRO_FACTS } from "~/config/comparisons";
import {
  MINIMUM_IPADOS_VERSION,
  MINIMUM_MACOS_VERSION,
  SITE_NAME,
} from "~/config/site";

const SLUG = "fastlane-snapshot";

export async function loader({ params }: Route.LoaderArgs) {
  const locale = params.locale;
  if (locale && !isLocaleCode(locale)) {
    throw data("Not Found", { status: 404 });
  }
  return { locale: (locale || "en") as LocaleCode };
}

export const meta: Route.MetaFunction = ({ matches, params }) =>
  buildComparisonMeta(SLUG, matches, (params.locale || "en") as LocaleCode);

const ROWS: ComparisonRow[] = [
  {
    factor: "License / cost",
    them: "MIT, free, open source",
    us: "Free tier + paid Pro (in-app purchase)",
  },
  {
    factor: "Distribution",
    them: "Ruby gem via bundler",
    us: "App Store",
  },
  {
    factor: "Primary job",
    them: "Capture app UI screenshots from XCUITest",
    us: "Design marketing screenshots from raw images",
  },
  {
    factor: "Source of screenshots",
    them: "Generated by running your test suite",
    us: "You provide them (any PNG/JPEG)",
  },
  {
    factor: "Device frames",
    them: (
      <>
        Via separate <code>frameit</code> tool — iPhone (up to 16), iPad, Mac,
        Android; ImageMagick required
      </>
    ),
    us: `Built in — ${SCREENSHOT_BRO_FACTS.frames}`,
  },
  {
    factor: "Headline / overlay text",
    them: (
      <>
        <code>frameit</code> overlays a single title from <code>.strings</code>
      </>
    ),
    us: "Multi-shape canvas: text, images, gradients, SVGs, custom fonts, alignment guides",
  },
  {
    factor: "Localization",
    them: (
      <>
        Languages listed in <code>Snapfile</code> drive a full test-suite
        re-run; titles localized via <code>.strings</code>
      </>
    ),
    us: SCREENSHOT_BRO_FACTS.localization,
  },
  {
    factor: "App Store Connect upload",
    them: (
      <>
        Via separate <code>deliver</code> tool (App Store Connect API)
      </>
    ),
    us: SCREENSHOT_BRO_FACTS.ascUpload,
  },
  {
    factor: "Google Play upload",
    them: (
      <>
        Via <code>supply</code>
      </>
    ),
    us: `${SCREENSHOT_BRO_FACTS.playUpload}; Android phone and tablet rows render alongside iOS in the same project`,
  },
  {
    factor: "tvOS / watchOS / visionOS",
    them: "snapshot officially supports iOS, tvOS, and watchOS screenshot capture. visionOS isn't called out in the snapshot docs.",
    us: "Apple Watch Ultra 3 frame included (no watchOS size preset); no tvOS or visionOS frames at this time",
  },
  {
    factor: "CI integration",
    them: "First-class — designed for headless CI runs",
    us: "Not a CI tool. Designed for interactive use on Mac, iPad or iPhone; a local MCP server on Mac lets agents drive edits",
  },
  {
    factor: "Setup time",
    them: "Hours: write UI tests, configure Snapfile, install ImageMagick, configure frameit, set up API key",
    us: "Minutes: drop screenshots in, pick frames, export",
  },
  {
    factor: "Ongoing maintenance",
    them: "UI tests must keep up with app changes; flaky-test risk",
    us: "Re-drop the new screenshots; layout and locale overrides stay",
  },
  {
    factor: "Platform requirement",
    them: "Mac with Xcode for capture; deliver runs anywhere Ruby does",
    us: SCREENSHOT_BRO_FACTS.platform,
  },
];

const FAQS: BlogFaqItem[] = [
  {
    question: "Is Fastlane snapshot free?",
    answer:
      "Yes. Fastlane is MIT-licensed open source. snapshot, frameit, and deliver are bundled in the same fastlane gem and have no usage fees. You pay in setup time and CI runner minutes.",
  },
  {
    question: "Can Screenshot Bro replace Fastlane snapshot?",
    answer:
      "Not directly. snapshot drives your app via XCUITest to capture raw UI screenshots; Screenshot Bro takes raw screenshots (from anywhere — simulator, real device, snapshot, or designer mocks) and turns them into marketing assets with frames, headlines, gradients, and locales. The two tools sit on different sides of the same pipeline.",
  },
  {
    question: "Can Fastlane snapshot replace Screenshot Bro?",
    answer:
      "Not for App Store marketing screenshots. snapshot captures clean app UI; frameit can wrap that UI in a device frame and add a localized title from .strings files. Screenshot Bro adds the design layer above that — multi-row layouts, spanning gradients, text shapes, custom fonts, on-device auto-translation, and direct App Store Connect and Google Play upload.",
  },
  {
    question: "Do I need Xcode and UI tests to use Screenshot Bro?",
    answer:
      "No. Screenshot Bro accepts any PNG or JPEG — drop screenshots from the iOS Simulator, a real device, snapshot output, designer mocks, or anything else. You only need UI tests if you want fully automated re-capture, which is what snapshot is for.",
  },
];

const RELATED: RelatedLink[] = [
  {
    href: "/blog/make-and-ship-screenshots-with-fastlane",
    label: "Fastlane: Make and Ship App Store Screenshots (2026 Guide)",
    description:
      "full Snapfile, Framefile.json, Deliverfile, and a GitHub Actions workflow.",
  },
  {
    href: "/blog/upload-screenshots-to-app-store-connect",
    label: "How to Upload Screenshots to App Store Connect",
    description: "the four ways to upload, and when to pick each.",
  },
  {
    href: "/blog/localize-app-store-screenshots",
    label: "Localizing App Store Screenshots Without Losing Your Mind",
    description:
      "patterns for managing many languages without exploding your workload.",
  },
  {
    href: "/docs/help",
    label: `${SITE_NAME} help & documentation`,
    description:
      "full reference for projects, rows, templates, locales, and the store upload flows.",
  },
  {
    href: "/vs",
    label: "All comparisons",
    description: "every tool compared against Screenshot Bro on one page.",
  },
];

export default function FastlaneSnapshotComparison() {
  return (
    <ComparisonShell
      slug={SLUG}
      tldr={
        <>
          these tools solve different problems. Fastlane <em>snapshot</em> is a
          UI-test-driven screenshot <em>capture</em> tool. {SITE_NAME} is a
          screenshot <em>design</em> tool. Most teams shipping to the App Store
          and Google Play end up using both — snapshot (or simulator captures)
          for the raw UI, then a design tool to add device frames, headlines,
          gradients, and locales.
        </>
      }
      faqs={FAQS}
      related={RELATED}
      ctaMessage="Drop simulator or device screenshots straight into Screenshot Bro and ship the marketing layer in minutes."
    >
      <h2>What each tool actually does</h2>

      <h3>Fastlane snapshot</h3>
      <p>
        <strong>snapshot</strong> is part of{" "}
        <a
          href="https://fastlane.tools/"
          target="_blank"
          rel="noopener noreferrer"
        >
          fastlane
        </a>{" "}
        (MIT-licensed). You write XCUITest cases that drive your real app and
        call <code>snapshot("01-Home")</code> at each frame you want to
        capture. fastlane runs the test suite across the device sizes and
        locales you list in <code>Snapfile</code> and saves a folder of clean
        PNGs. It supports iOS, tvOS, and watchOS, and tests can be written in
        Swift or Objective-C.
      </p>
      <p>Two adjacent fastlane tools usually come along:</p>
      <ul>
        <li>
          <strong>frameit</strong> — wraps each captured screenshot in a device
          frame and optionally overlays a localized title from a{" "}
          <code>.strings</code> file. Requires ImageMagick. Frame catalog
          covers iPhone, iPad, Mac, and Android, and at the time of writing the
          latest iPhone frame in{" "}
          <a
            href="https://github.com/fastlane/frameit-frames/tree/gh-pages/latest"
            target="_blank"
            rel="noopener noreferrer"
          >
            frameit-frames
          </a>{" "}
          is iPhone 16 — iPhone 17 frames are not yet shipped.
        </li>
        <li>
          <strong>deliver</strong> — uploads framed screenshots (and optionally
          metadata) to App Store Connect. Pairs with <code>supply</code> for
          Google Play.
        </li>
      </ul>
      <p>
        The fastlane project is actively maintained and has 41k+ stars on
        GitHub.
      </p>

      <h3>{SITE_NAME}</h3>
      <p>
        {SITE_NAME} is a native Mac, iPad and iPhone app (Swift + SwiftUI,
        macOS {MINIMUM_MACOS_VERSION}+ or iOS/iPadOS {MINIMUM_IPADOS_VERSION}
        +). It does not capture screenshots from a running app — you bring your
        own raw images, by drag-and-drop or one-click capture from the iOS
        Simulator on Mac, and the app handles the design and ship side: device
        frames, multi-shape layouts, gradients, custom fonts, 81 language
        presets with on-device auto-translation, and direct upload to App Store
        Connect and Google Play. The free tier is unlimited in time (1 project,
        3 rows, 5 templates per row) and includes store upload; Pro lifts those
        limits.
      </p>

      <h2>Side-by-side</h2>
      <ComparisonTable competitor="Fastlane snapshot" rows={ROWS} />

      <h2>When to pick Fastlane snapshot</h2>
      <ul>
        <li>
          Your app changes frequently and you want screenshots that always
          reflect the current build, regenerated by CI.
        </li>
        <li>
          You ship dozens of locales and the alternative is manually re-shooting
          each one every release.
        </li>
        <li>
          You already have UI tests (or can justify writing them) and your team
          is comfortable with Ruby/fastlane configuration.
        </li>
        <li>
          You have a deterministic CI pipeline (GitHub Actions, Bitrise, Xcode
          Cloud) where adding a 15-minute screenshot lane is acceptable.
        </li>
        <li>
          Your marketing screenshots are simple — device frame plus a single
          localized title is enough — so frameit covers the design layer.
        </li>
      </ul>

      <h2>When to pick {SITE_NAME}</h2>
      <ul>
        <li>
          You want a polished marketing layout — headlines, gradients, spanning
          backgrounds, multi-shape compositions, branded fonts — that
          frameit&apos;s title-overlay model can&apos;t express.
        </li>
        <li>
          You ship to both App Store and Google Play and want to manage and
          upload both sets from one project.
        </li>
        <li>
          You don&apos;t have UI tests and would rather drop simulator
          screenshots in than write XCUITest scaffolding.
        </li>
        <li>
          You need iPhone 17 / iPhone Air / iPad Pro / MacBook Pro 14"/16" /
          Apple Watch Ultra 3 frames today.
        </li>
        <li>
          You prefer a GUI to a YAML/Ruby config, and a one-click
          export-then-upload over a CI pipeline.
        </li>
        <li>
          You want auto-translation that runs on-device — no API keys, no
          third-party servers, no usage tracking.
        </li>
      </ul>

      <h2>Use both: the typical pipeline</h2>
      <p>The two tools fit together cleanly. A common shipping flow:</p>
      <ol>
        <li>
          <strong>Capture</strong> raw UI screenshots with{" "}
          <code>fastlane snapshot</code>, or by hand from the iOS Simulator.
          The output is a folder of clean PNGs.
        </li>
        <li>
          <strong>Design</strong> in {SITE_NAME}: drop the folder onto the
          canvas (it routes shots to the right device row by pixel size), add
          device frames, headlines, gradients, and locales.
        </li>
        <li>
          <strong>Export</strong> a tree of locale × row × template PNGs.
        </li>
        <li>
          <strong>Upload</strong> directly from {SITE_NAME} with your App Store
          Connect API key or Google Play service account, or hand the export
          folder to <code>fastlane deliver</code> / <code>supply</code> if
          you&apos;ve already wired them up.
        </li>
      </ol>
      <p>
        Teams that want fully automated capture-to-upload usually keep fastlane
        in the loop for the capture step and use {SITE_NAME} for the design +
        upload. Teams that don&apos;t have UI tests skip fastlane entirely and
        use {SITE_NAME} end-to-end.
      </p>

      <h2>Frequently confused points</h2>

      <h3>&quot;Doesn&apos;t frameit handle the design?&quot;</h3>
      <p>
        frameit overlays a device frame and one localized title from a{" "}
        <code>.strings</code> file. It does not produce multi-shape layouts,
        spanning gradients, custom typography, or branded backgrounds. If your
        final asset is &quot;device + one line of text,&quot; frameit is
        enough. If it&apos;s &quot;two devices on a gradient with a headline
        that flows across them, plus a logo and a feature callout,&quot; you
        need a design tool.
      </p>

      <h3>&quot;Doesn&apos;t snapshot already do everything?&quot;</h3>
      <p>
        snapshot is a capture tool — it drives your app via XCUITest and saves
        the result. It does not add device frames, headlines, or marketing
        design. The full fastlane store-screenshot pipeline is three tools:{" "}
        <code>snapshot</code> + <code>frameit</code> + <code>deliver</code>.
      </p>

      <h3>&quot;Can {SITE_NAME} capture screenshots from my app?&quot;</h3>
      <p>
        Not by running tests. {SITE_NAME} accepts raw images you provide — drag
        and drop from anywhere. On the Mac there is a capture button on each
        template that pulls the most recent iOS Simulator screenshot directly
        into the canvas after a one-time helper install, which covers the
        manual flow, but there is no XCUITest integration.
      </p>

      <h3>&quot;Is fastlane abandoned?&quot;</h3>
      <p>
        No. The repository is actively maintained — version 2.233.1 was
        released in April 2026 — with 41k+ stars and continuous commit
        activity. The project is a stable, production-grade tool used across
        the Apple developer ecosystem.
      </p>

      <h2>The honest bottom line</h2>
      <p>
        If you read this page hoping for &quot;X is better than Y&quot; —
        that&apos;s the wrong frame. snapshot solves <em>capture</em> and{" "}
        {SITE_NAME} solves <em>design + upload</em>. The right question is
        which side of the pipeline matters more to your release cycle, and
        whether you want a CI-native or interactive workflow for each side.
      </p>
      <p>
        If your screenshots are already good enough as raw UI plus a single
        localized title, fastlane is enough. If you want the marketing-design
        layer (or you don&apos;t want to write UI tests), drop {SITE_NAME} into
        the pipeline.
      </p>
    </ComparisonShell>
  );
}
